### ISSUE TITLE
Properly handle the case where there is no application.json

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#100]
Currently, an error is caught and ignored.

**Comment by epuidokas** [comment]
How should this be handled?
1. Throw warning, attempt to copy application.json from the default archetypes into application folder and continue execution
2. Throw an error and serve a 500
3. Something else?

When should this be handled (at startup, at request time, or both)?

**Comment by isao** [comment]
an app with no application.json could still serve mojits via htpp://host/@MojitName/action

It's an unlikely usecase, but I'd say no change, or generate a warning.
