### ISSUE TITLE
build hybrid app regression

### ISSUE THREAD

**Issue by isao** [YahooArchive/mojito#1006]
from Ji liang 2/24:

DP-Integration-Test is failing on mojito 0.5.4-133-g443bf5e

To reproduce this:
1.install latest IDE plugins from here:
http://<redacted>/update,
 download the latest Mojito, CRT by IDE download manager.
2. Create new mojito project,right click the project ->content menu->run
as -> ipad app on simulator
3. Then index rendered was not right, and expand the
app/artifacts/builds/hybridapp/yahoo.application.appname/ there was no
index.html.

Ji liang

**Comment by caridy** [comment]
It might be related to PR #997 and the upcoming fix #1007

**Comment by isao** [comment]
fix confirmed by Ji Liang
