### ISSUE TITLE
Getting rid of the Foo

### ISSUE THREAD

**Issue by akshar100** [YahooArchive/mojito#1014]
Whenever we run 'mojito create mojit SomeMojit' it generates a lot of code for us. However I do not see any point in appending the Model names with "Foo". It gets very irritating once you create multiple mojits and have to modify all the files were there are references to "SomeMojitModelFoo".

**Comment by rmadhuram** [comment]
+1

**Comment by drewfish** [comment]
The trick is that you can have more than one model in each mojit.  In that case you'll need a way to distinguish them.  So, giving your models an explicit name (in the YUI module name) is considered a good practice, to make room for the future.

**Comment by isao** [comment]
I agree the "full" archetypes have their quirks. closing here, tracking at yahoo/mojito-cli-create#12
