### ISSUE TITLE
Setting `staticHandling.prefix=""` does not allow you to remove the prefix to the static URL

### ISSUE THREAD

**Issue by zhouyaoji** [YahooArchive/mojito#1015]
The Store allows you to use an empty string to configure your app _not_ to have a prefix for static URLs:

`mojito/lib/app/autoload/store.client.js`

```
// This value could be an empty string so we have to do a real check.
this.staticPrefix = '/static';
          if (this.appConfig && this.appConfig.staticHandling &&

this.appConfig.staticHandling.hasOwnProperty('prefix')) {
              this.staticPrefix = (this.appConfig.staticHandling.prefix
?
'/' +
                  this.appConfig.staticHandling.prefix : '');
          }
```

Unfortunately, the Resource Store, however, seems to override this behavior:

mojito/lib/app/addons/rs/url.js

```
   _calcResourceURL: function(res, mojitRes) {
              var fs = res.source.fs,
                  relativePath = fs.fullPath.substr(fs.rootDir.length
+ 1),
                  urlParts = [liburl.resolve('/', (this.config.prefix
||  'static'))];
```

I've actually played around with both files and changing the value in
`rs/url.js`, allowing you to define the default prefix or have none at all.

**Comment by rwaldura** [comment]
All right Joe! Nice work.
We’re going to make a developer out of you ☺

**Comment by caridy** [comment]
We will remove the ability to use a prefix due the fact that static assets should not be coming from the app origin, but from CDN, and for development we will use a "fixed" path, same for html5 apps. Closing this.
