### ISSUE TITLE
Putting  a README.md in the mojits/ directory causes mojito to not load

### ISSUE THREAD

**Issue by gotwarlost** [YahooArchive/mojito#1017]
```
$ touch mojits/README.md
$ ./node_modules/mojito/bin/mojito start --context environment:development
info: (mojito-resource-store): Store initialized
info: (mojito-resource-store): Store initialized

/tmp/ui/node_modules/mojito/lib/app/addons/rs/config.js:149
                            throw new Error("Error parsing file: " + fullPath 
                                  ^
Error: Error parsing file: /tmp/ui/mojits/README.md/definition.json
```

Not a big deal but a bug all the same.

**Comment by gotwarlost** [comment]
Note how it thinks that `README.md` is a directory. If this is common code, this bug may have other subtler manifestations.

**Comment by drewfish** [comment]
Looks like a bug in the resource store.

**Comment by drewfish** [comment]
I think the fix entails added a check in lib/app/autoload/store.server.js _preloadDirMojit() to make sure that the `dir` argument is actually a directory (and just return if it isn't).
