### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by rmadhuram** [YahooArchive/mojito#1020]
Says "Mojito mayor version"

**Comment by drewfish** [comment]
Where are you seeing this?  I couldn't find "mayor" when I grepped through the source code.

**Comment by rmadhuram** [comment]
Sorry the context is not carried over when I click on "Report a bug" 
It is on this page:http://developer.yahoo.com/cocktails/shaker/shaker_starting.html#running-shaker
"Nontherless here a table where you can find the most stable version of Shaker for each mojito mayor version:"

**Comment by zhouyaoji** [comment]
Hi rmadhuram, I've updated the Shaker docs for you, but if you see issues with the Shaker docs in the future, please file an issue in the yahoo-shaker GH repository: https://github.com/yahoo/mojito-shaker/issues

Thanks again for helping to improve the documentation.

**Comment by rmadhuram** [comment]
Thanks Joe.
