### ISSUE TITLE
Documentation for logging doesn't specify where logs are stored

### ISSUE THREAD

**Issue by lexander** [YahooArchive/mojito#1025]
Not very useful to have logging if you don't tell people where to view the log files.

**Comment by rwaldura** [comment]
@zhouyaoji 
@lexander thanks for the report. Where should the log location be specified? Which section of the doc is it missing from?

**Comment by lexander** [comment]
d'oh, I thought that the link to "Report an issue on this page" would include the location from which I came as a parameter. 

Here's the page where I'd expect to find documentation on default log locations and how to configure those locations - http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_logging.html

**Comment by caridy** [comment]
@lexander mojito does not write logs into a file, that's not something the framework will do, but the underlaying infrastructure, in this case node.js. Mojito simply writes into the node.js console, whatever node.js does with the logs, dumping them into a file, or transmit them into an aggregated hub for multiple cores, or whatever other crazy idea people decide to implement has very little to do with mojito.

Aside from that, mojito is smart enough to detect if you're using TTY or not, to add colors into the logs or not, in case you boot the application using sparks or any other similar runner, and it works just fine with heroku and nodejitsu log aggregators.

**Comment by lexander** [comment]
Ah, well then perhaps the documentation (this bug wasn't about what Mojito does or does-not do) should call that out. Here's a pull request with the change https://github.com/yahoo/mojito/pull/1045
