### ISSUE TITLE
Invalid link in Shaker document

### ISSUE THREAD

**Issue by rmadhuram** [YahooArchive/mojito#1033]
In http://developer.yahoo.com/cocktails/shaker/shaker_starting.html,
Clicking on the "Shaker: Example" link gives a 404.

Raj

**Comment by zhouyaoji** [comment]
Thanks, Raj. I've fixed the link. Sorry if I asked this before, but for Shaker doc issues, can you file the issue in the Shaker GH repo (https://github.com/yahoo/mojito-shaker).

**Comment by rmadhuram** [comment]
Thanks Joe. Sure. I'll do it from next time onwards.

Raj

**Comment by zhouyaoji** [comment]
Great, thanks!
