### ISSUE TITLE
Firefox loads wrong page from cache.

### ISSUE THREAD

**Issue by kevinhasslinger** [YahooArchive/mojito#1039]
A Mojito based Webpage which contains several subpages: a, b, c etc..
Sometimes I get randomly the problem in firefox, that firefox requests page 'a', but mojito delivers 'b'. After clearing the cached web content, this problem is solved for some time.
Never had this problem in Chrome.

There is no problem with routing in my mojito application, i clearly see that mojito thinks 'b' is requested.
Not sure if this is a bug in firefox or mojito. Also I'm sure its hard to monitor, because it looks like it happens randomly.

Firefox version where observed this problem: 19.0.2 (the current one)

**Comment by rwaldura** [comment]
Ooooh very strange! @kevinhasslinger we're going to need your help debugging this one, because it sounds very very peculiar. Could you generate some automated traffic against your app, and identify a reproducible test case? That would really help narrow down the problem.

**Comment by caridy** [comment]
@kevinhasslinger when that happens, do you see the request for "a" in the access logs while mojito responds with "b"? I wonder if the problem is happening before the request gets to mojito.

**Comment by kevinhasslinger** [comment]
mojito shows 'b' in access log (="thinks" from original post) is requested and delivers 'b'. Which means this is either a bug in firefox, or deep down in mojito/express?
Maybe a tool like wireshark can tell me what url firefox is really requesting, or is there a more pleasant way to do that? 
mojito current version 0.5.6 by the way.

**Comment by rwaldura** [comment]
Wireshark is cool, and will certainely show exactly what's happening on the wire.
But I'd start with Firebug, see what the "Net" panel says.

**Comment by kevinhasslinger** [comment]
I know this report is a month old, but until today I didn't got this weird behavior again.
It's definitely a problem with Firefox: in Wireshark I can see that Firefox is requesting /b and mojito delivers that correctly. Even if I call localhost:8666/a directly in FF from Adress bar, FF still asks for localhost:8666/b.

Sorry for bothering mojito as the reason for this.

**Comment by rwaldura** [comment]
Thanks for following up!
