### ISSUE TITLE
Mojito started on http://127.0.0.1:8666/

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#1043]
See http://developer.yahoo.com/forum/Yahoo-Mojito/Binding-Mojito-to-another-address/1363299307784-f3079bf9-e416-4796-9621-63ecf246166a

The CLI message is wrong; in reality the process is bound to 0.0.0.0.

**Comment by rwaldura** [comment]
@isao who's working on the CLI

**Comment by isao** [comment]
mojito's underlying express/connect/node http server is started without specifying a host, and afaict mojito ends up listening to "connections directed to any IPv4 address (INADDR_ANY)." [link](http://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)

OMM:

```
% netstat -an | grep 8666
tcp4       0      0  127.0.0.1.8666         127.0.0.1.60749        ESTABLISHED
tcp4       0      0  127.0.0.1.60749        127.0.0.1.8666         ESTABLISHED
tcp4       0      0  127.0.0.1.8666         127.0.0.1.60746        ESTABLISHED
tcp4       0      0  127.0.0.1.60746        127.0.0.1.8666         ESTABLISHED
tcp4       0      0  127.0.0.1.8666         127.0.0.1.60745        ESTABLISHED
tcp4       0      0  127.0.0.1.60745        127.0.0.1.8666         ESTABLISHED
tcp4       0      0  *.8666                 *.*                    LISTEN   
```

... bout http://0.0.0.0:8666 also works

**Comment by rwaldura** [comment]
@isao you're entirely correct.
Let's change the startup message to "Mojito started on on port 8666" because that's what it does.
