### ISSUE TITLE
MQSG tweaks

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#1060]
- Include a Y! copyright at bottom: _Copyright (c) 2011-2013, Yahoo! Inc.  All rights reserved._
- Drop the Cocktails logo, use Mojito logo instead, and link to http://developer.yahoo.com/cocktails/mojito/
- Replace _Interested in how this web app is built? Please visit our git project page for more info._ at bottom with: [Learn more about this application.](https://github.com/yahoo/mojito/tree/develop/examples/quickstartguide)
- The product name is "Mojito Quickstart Guide", this string should be used in TITLE and H1 tags.

**Comment by rwaldura** [comment]
![mojito-logo-white-bkg](https://f.cloud.github.com/assets/504234/341641/924da8ac-9d76-11e2-969b-0b620e19beaf.png)

Logo to use

**Comment by rwaldura** [comment]
@luchenghan

**Comment by dormfood** [comment]
Instead of replacing Cocktails logo, mojito logo is used at the top as title.
Please see http://y.ahoo.it/mqsg
Thanks.

**Comment by rwaldura** [comment]
I'm sorry, there was some confusion: please replace the "Powered by Cocktails" logo with a Mojito logo.
@luchenghan 
The title should be all text.

**Comment by dormfood** [comment]
Done. Please visit http://y.ahoo.it/mqsg
PR issued, waiting for merge.
Thanks.
