### ISSUE TITLE
Should not use require('path').normalize() for URL paths

### ISSUE THREAD

**Issue by ekashida** [YahooArchive/mojito#1063]
https://github.com/yahoo/mojito/commit/ea75f3aa8027e5000e7e75ebe0dde7e704ef047a#lib/app/middleware/mojito-handler-tunnel-parser.js
This will cause problems in the Windows version of node since Windows uses backslashes in file system paths.

**Comment by isao** [comment]
that diff looks ok, the docs [say](http://nodejs.org/api/path.html#path_path_normalize_p) "On Windows backslashes are used.". and those paths are for middleware/uri's seems. 

but I'm sure there are other places where this issue does apply.

**Comment by caridy** [comment]
Closing after merging #1103
