### ISSUE TITLE
DOC: Frame Mojit chapter: broken link for Custom Frame example full code

### ISSUE THREAD

**Issue by lazybean** [YahooArchive/mojito#1096]
Hi,

There is a broken link in the doc: https://github.com/yahoo/mojito/blob/develop/docs/dev_guide/topics/mojito_frame_mojits.rst#example-1

This  "see `frame_app <https://raw.github.com/caridy/Mojito-Apps/master/frame_app>`_." goes to a 404 page.

Take care

**Comment by zhouyaoji** [comment]
Thanks, @lazybean. I've corrected the link.

**Comment by lazybean** [comment]
Thanks a lot!
