### ISSUE TITLE
JavaScript error in mojito-client.client.js after refreshView with composites

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#11]
- I have a mojit that uses ac.composite.invoke() to create child mojits
- Each of these child mojits has a binder of its own. When clicking “Search” the XXX binder issues an mp.refreshView() call.
- The number of child mojit instances will vary from refresh-to-refresh (currently just using Math.random() to achieve this)
- Eventually if you hit ‘Search’ enough times, you’ll get a Javascript error on the client.

**Comment by caridy** [comment]
closing old ticket.
