### ISSUE TITLE
Mojito should provide a way fine-grained way to target runtime environments

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#112]
Currently, files with "common" affinity that need to specify a small portion of code to be server- or client-only must refactor the code into two files, one with "client" affinity and one with "server" affinity.

This is a very high-overhead approach and a barrier to getting useful work done.

Instead, Mojito should provide a low-overhead way to meet this requirement. Two potential approaches:
1. Provide targeting of configuration to client or server. Then code could read the config key.
2. Provide an API to detect the runtime environment such as Y.mojito.isClient() => Boolean or Y.mojito.getRuntime() => string (ex. "client").

**Comment by caridy** [comment]
@add0n that feature already exists. In the server or in the client, you can access to ac.context.runtime in the controller. In the binder you have access to mojitProxy.context.runtime, it will have:

server or client, depending on the runtime.

About the other part of the request, I don't think configuration are any better than a descriptor in the filename.
