### ISSUE TITLE
Doc: Multiple Mojits: Confusing routes.json

### ISSUE THREAD

**Issue by lazybean** [YahooArchive/mojito#1124]
Thanks for mojito.

In the example for multiple mojits , http://developer.yahoo.com/cocktails/mojito/docs/code_exs/multiple_mojits.html

The 'routes.json' is quite puzzling. 
Why do we need routes for the children mojit(header, footer, body)? 
I you try to get those path, you'll have an error.
Having only the "root" route is fine. No?

``` javascript
[
  {
    "settings": ["master"],
    "root": {
      "verbs": ["get"],
      "path": "/",
      "call": "frame.index"
    },
    "header": {
      "verbs": ["get"],
      "path": "/header",
      "call": "header.index"
    },
    "body": {
      "verbs": ["get"],
      "path": "/body",
      "call": "body.index"
    },
    "footer": {
      "verbs": ["get"],
      "path": "/footer",
      "call": "footer.index"
    }
  }
]
```

This should be enough.

``` javascript
[
  {
    "settings": ["master"],
    "root": {
      "verbs": ["get"],
      "path": "/",
      "call": "frame.index"
    }
  }
]
```

Or do I miss the point?

**Comment by caridy** [comment]
@lazybean I'm with you on this one, it should be a single route.

/ping @zhouyaoji
