### ISSUE TITLE
mojito command not found after npm install

### ISSUE THREAD

**Issue by ginader** [YahooArchive/mojito#113]
$ npm install mojito
npm http GET https://registry.npmjs.org/mojito
npm http 200 https://registry.npmjs.org/mojito
npm http GET https://registry.npmjs.org/mojito/-/mojito-0.0.1.tgz
npm http 200 https://registry.npmjs.org/mojito/-/mojito-0.0.1.tgz
mojito@0.0.1 ./node_modules/mojito

$ mojito create app simple hello
-bash: mojito: command not found

$ node -v
v0.6.11

$ npm -v
1.1.1

**Comment by mojit0** [comment]
I've updated the README file to reflect the proper installation. Because there's a "binary" for Mojito you currently have to do a global install as well. Proper steps should be:

npm install -g mojito
npm install mojito

The first command will put the mojito command where it should be found.

**Comment by ginader** [comment]
that did the trick!
thanks :-)
