### ISSUE TITLE
quickstart guide says to install mojito globally

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#1133]
http://developer.yahoo.com/cocktails/mojito/docs/getting_started/quickstart.html

**Comment by isao** [comment]
@zhouyaoji you can use this as the basis http://git.io/qaSSdw .. I will make those trello cards I promised later today, thanks!

**Comment by zhouyaoji** [comment]
I've updated the quickstart with instructions to install mojito-cli.
