### ISSUE TITLE
In a mojit controller the config is lost when the binder refreshView. 

### ISSUE THREAD

**Issue by lazybean** [YahooArchive/mojito#1135]
version affected: 0.6.0 and 0.5.9pr1
No problem on 0.5.8 

See the Example code in the gist.
https://gist.github.com/lazybean/5628695

When you load the page a first time. config will contain "foo":42.
When you click on the mojit (triggers a refreshView) config is empty.

Workaround is to use an instance mojit as a base. As shown it @caridy 's gist.
https://gist.github.com/caridy/5628753

**Comment by caridy** [comment]
A note was added into the release note. This is a regression that will be patched soon.

**Comment by caridy** [comment]
Workaround described here:
https://github.com/yahoo/mojito/issues/1046#issuecomment-15330353

Closing in favor of issue #1046
