### ISSUE TITLE
An error on a coding example for running Mojito on windows

### ISSUE THREAD

**Issue by houyhnhnm** [YahooArchive/mojito#1145]
An error occured when i made the adding_view_engines code example. the Mojit default worked fine in views/default_ve.hb.html but the ejs views/added_ve.ejs.html returns an error.
I am using Mojito 0.6.0

Error: ENOENT, no such file or directory 'C:\MyComp\mojito\project\adding_view_engines[object Object]' It is the only example that didnt work out as it was supposed to for me.

I assume the ejs module's interpretation isnt being received by the mojito on windows, in some fashion. I used npm within the mojito app and the ejs installed without issue. But, the result from the ejs view states ENOENT as well as the response above from the command prompt.

I imagine it is the ejs addon engine itself
https://github.com/yahoo/mojito/blob/master/examples/developer-guide/adding_view_engines/addons/view-engines/ejs.server.js

**Comment by caridy** [comment]
mojito should work just fine in windows. If you have any issue, ping @juandopazo.

**Comment by houyhnhnm** [comment]
It is working fine for me now Caridy:) thanks I should have closed this issue myself. I must become a better community member of github: But I am growing.
