### ISSUE TITLE
Malformed markup showing up in the doc

### ISSUE THREAD

**Issue by imalberto** [YahooArchive/mojito#1149]
The paragraph below has incorrect / malformed markup showing up on the doc site.

Link: http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_using_contexts.html#context-configs-custom

See section "Creating Custom Contexts"

The Mojito framework defines default contexts that developers can map configurations to. These default contexts are defined in the file dimensions.json https://github.com/yahoo/mojito/blob/develop/source/lib/dimensions.json`_ found in the Mojito source code. Developers can create an application-level``dimensions.json to define custom contexts that can be mapped to configurations as well.

**Comment by zhouyaoji** [comment]
Fixed, thanks!
