### ISSUE TITLE
No Sanity Check in route-maker.common.js causing error on client side in IE-7 IE-8

### ISSUE THREAD

**Issue by chetanankola** [YahooArchive/mojito#1151]
https://github.com/yahoo/mojito/blob/develop/lib/app/autoload/route-maker.common.js#L124

route.requires[matches[i].substr(1)] = '[^&]+';

fails when matches[i] is a number! 

This is urgent for us since its breaking our app on ie 6 and greater!

**Comment by isao** [comment]
@chetanankola can you provide a repro, or gist of the routes.json?

**Comment by caridy** [comment]
@isao can we close this?

**Comment by jenny** [comment]
Will be avail in 0.6.1 this week!
