### ISSUE TITLE
not able to use mojito-data-addon if the mojit is lazy loaded via mojitProxy.invoke

### ISSUE THREAD

**Issue by ghost** [YahooArchive/mojito#1159]
In my mojit I have two actions: "index" and "lazy", where "index" will invoke "lazy" from binder. The mojito-data-addon is included but in "lazy" action, when calling ac.data.set(), there is an error:

TypeError: Object #<Object> has no method 'set'

Apparently it is because mojito passing a `data` property in invoke command, and it make data addon failed to init itself.
https://github.com/yahoo/mojito/blob/develop/lib/app/autoload/mojit-proxy.client.js#L204
https://github.com/yahoo/mojito/blob/develop/lib/app/addons/ac/data.common.js#L25

I created a simple app the demo the issue:
https://git.corp.yahoo.com/yiwu/demo-lazyload-issue

**Comment by caridy** [comment]
I was able to reproduce this. thanks for the repro case, I will try to land a fix asap.
