### ISSUE TITLE
Sometimes viewing documentation results in 404.

### ISSUE THREAD

**Issue by oyving** [YahooArchive/mojito#1176]
Reproduce by going to http://developer.yahoo.com/cocktails/mojito/docs/quickstart/ and refresh a few times. Sometimes you will get a 404.

**Comment by zhouyaoji** [comment]
The quickstart was moved a while ago to the "Getting Started" chapter, but YDN just recently pulled the old quickstart from the site. You can view the quickstart at the following URL: http://developer.yahoo.com/cocktails/mojito/docs/getting_started/quickstart.html

**Comment by oyving** [comment]
That may be, but then the "Get Started" link at http://developer.yahoo.com/cocktails/mojito/ is pointing to the wrong resource.
