### ISSUE TITLE
Invalid context dimension should return HTTP 4xx error

### ISSUE THREAD

**Issue by jlecomte** [YahooArchive/mojito#1183]
Currently, mojito returns HTTP 5xx error with a string "Internal Server Error". Instead, it should return HTTP 4xx error with a string "Bad Request".

**Comment by caridy** [comment]
makes sense!

**Comment by caridy** [comment]
Now in mojito-next (0.9.x), you can simply control any error accordingly:

http://expressjs.com/guide.html#error-handling

Although, I think this enhance makes sense, and I wonder how to detect it today thru express' error handling method. Feel free to reopen this.
