### ISSUE TITLE
Document the API methods for the Data addon (Data.common class).

### ISSUE THREAD

**Issue by zhouyaoji** [YahooArchive/mojito#1192]
The API documentation for the Data.common class says that this class  doesn't provide any methods, properties, attributes, or events. The general documentation covers how to use the Data addon, but developers need to be able to refer to the API docs. It's simply a matter of adding the YUIDoc tags and descriptions to the source code.

**Comment by zhouyaoji** [comment]
Looks good, but I think we also need to document that the methods accessed through the `data` and `pageData` namespaces are available from the `mojitProxy` object.
- http://developer.yahoo.com/cocktails/mojito/api/classes/MojitProxy.html#property_data
- http://developer.yahoo.com/cocktails/mojito/api/classes/MojitProxy.html#property_pageData

**Comment by isao** [comment]
I added get/set `@method` tags for mp.data and mp.pageData, and changed mp.data and mp.pageData `@type` from Object to Model.Vanilla so class docs are linked. Also added link to Y.Model.

The structure is a bit deep/awkward, but it is hopefully more helpful. See yahoo/mojito#1201
