### ISSUE TITLE
Mojito doesn't catch syntax errors in `routes.json`.

### ISSUE THREAD

**Issue by zhouyaoji** [YahooArchive/mojito#1193]
If the `routes.json` has malformed JSON, the Mojito application does not throw an error, and when a request is made to one of the defined routing paths, the response body (shown on the page) is the string "OK", which isn't okay.

**Comment by caridy** [comment]
Hmm, this is probably affecting any JSON file, not only routes.json.

**Comment by caridy** [comment]
@imalberto is this fixed in mojito-next? what happen if there is a malformed `routes.json`? feel free to close this.

**Comment by imalberto** [comment]
This should throw the exception for malformed json: 

https://github.com/yahoo/mojito/blob/develop/lib/util.js#L115
