### ISSUE TITLE
Server crashes during /tunnel in util.common.js

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#12]
In certain scenarios, the server will crash with a Function.APPLY_OVERFLOW error in util.common.js. Will attach a stack and descriptions of the scenarios shortly.

**Comment by mojit0** [comment]
Pull request is now in for a patch that should resolve this.

**Comment by isao** [comment]
fixed by 17f264713aacd41b95b64be47236a55455d3fa62
