### ISSUE TITLE
Doc: Refreshing View does not mention onRefreshView

### ISSUE THREAD

**Issue by lazybean** [YahooArchive/mojito#1212]
Hi,

There http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_binders.html#mojito-binders-refresh-views , there is no word about onRefreshView. 

It is not mentioned that the binder's onRefreshView function will be called after refreshed, and that is can/should be used to detach/reattach event.

It can be confusing.

**Comment by zhouyaoji** [comment]
Thanks, @lazybean. @caridy can you take a look at my updated draft? I added short explanation and a code snippet using `onRefreshView`. Thanks!

https://github.com/zhouyaoji/mojito/blob/docs_onRefreshView/docs/dev_guide/intro/mojito_binders.rst#refreshing-views

**Comment by lazybean** [comment]
Thanks à lot @zhouyaoji ! Updated version looks good.

**Comment by zhouyaoji** [comment]
Great, I've updated the documentation on YDN as well. Thank you!

http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_binders.html#refreshing-views
