### ISSUE TITLE
Tutorial page has dead link for Quickstart 

### ISSUE THREAD

**Issue by tc** [YahooArchive/mojito#1222]
http://developer.yahoo.com/cocktails/mojito/docs/getting_started/mojito_getting_started_tutorial.html

The Quickstart link in the body points to 
http://developer.yahoo.com/cocktails/mojito/docs/quickstart

The right link is
http://developer.yahoo.com/cocktails/mojito/docs/getting_started/quickstart.html

**Comment by zhouyaoji** [comment]
Thanks, the link has been corrected!
