### ISSUE TITLE
Tutorial example doesn't work

### ISSUE THREAD

**Issue by 4score** [YahooArchive/mojito#1229]
On the very first tutorial. Here's the link:

http://developer.yahoo.com/cocktails/mojito/docs/getting_started/mojito_getting_started_tutorial.html

Quite possibly the most pathetic tutorial attempt ever.

**Comment by zhouyaoji** [comment]
Thanks, the module name in the boilerplate code created for model changed, so the tutorial should have been updated but wasn't. I'm in the process of updating the tutorial now. I apologize for the error. I'll have the updated documentation published as soon as possible. Aside from the error, please let me know if you have other feedback.
