### ISSUE TITLE
Please lower RS log messages for duplicate resources from "info" to "debug"

### ISSUE THREAD

**Issue by jlecomte** [YahooArchive/mojito#1238]
Currently, when starting our app, we are getting tons of lines like the following:

info: (mojito-resource-store): 
skipping duplicate package yahoo-utils-url
skipping  /git-data/apps/search-apps-news/node_modules/yahoo-mojits-search-time-filter/node_modules/yahoo-utils-url
prev used /git-data/apps/search-apps-news/node_modules/yahoo-mojits-search-bread-crumb/node_modules/yahoo-utils-url

Nobody cares about those log messages, they scare n00bs, they hide more important messages, and they are a symptom of an issue with Mojito/YUI, not with the way the app itself is designed (Indeed, the same package often needs to be in multiple parts of the node_modules hierarchy in order to be able to share packages transparently across apps, etc.)

My proposal: drop the log level for those messages from "info" to "debug". Even better would be to have a custom log level for non serious messages emitted by the resource store itself! Not sure whether that's possible...

**Comment by caridy** [comment]
Makes sense! I will add it to trello.

**Comment by caridy** [comment]
This is done in mojito-next (0.9)
