### ISSUE TITLE
a left curly brace is missing

### ISSUE THREAD

**Issue by nccuMis** [YahooArchive/mojito#1246]
In the example of the basic structure of Controller in http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_mvc.html
,
it seems that a left curly brace is missing:
YUI.add('{mojit_name}', function(Y, NAME) "{"

**Comment by zhouyaoji** [comment]
Thanks nccuMis, I've fixed the type.

**Comment by nccuMis** [comment]
Good.

2013/12/6 Joe Catera notifications@github.com
