### ISSUE TITLE
Unable to get mojito running on nodejitsu

### ISSUE THREAD

**Issue by triptych** [YahooArchive/mojito#125]
After creating a nodejitsu acct and trying to deploy a mojito app a number of issues arose:
1) apparently the version of express used by mojito is out of date and has known issues - preventing nodejitsu to downgrade to that version.

2) some comments from the #nodejitsu IRC channel : https://github.com/nodejitsu/haibu/blob/master/lib/haibu/plugins/coffee.js I think with an approach like this you could get "start": "mojito app.js" to work in haibu, and by extension on nodejitsu

This is really meant as a way to get the ball rolling on compat between nodejitsu.com and mojito.

**Comment by rwaldura** [comment]
triptych: I'm going to close this issue in favor of issue #126 instead, okay?
https://github.com/yahoo/mojito/issues/126
Clearly a duplicate.

**Comment by triptych** [comment]
Sounds good, thanks for the update.
