### ISSUE TITLE
easy way to get contextualized models

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#1251]
The current `ac.models.get()` takes the YUI module name as the argument. This means that I (as an app developer) need to know ahead of time which YUI module to use for a model.

The feature request is to augment `ac.models.get()` to take the model name (for example, `foo` for `models/foo.server.js`) and to use the correct model for the current context.

**Comment by drewfish** [comment]
As it turns out, the mojit resolution process already has this exact mapping. (It can be found at `ac.command.instance.models`.)

For backwards compatibility we should probably first look in `Y.mojito.models[name]` then fallback to `Y.mojito.models[instance.models[name]]` which implements this feature. (Plus good error checking of course.)

**Comment by caridy** [comment]
Sounds good to me!
