### ISSUE TITLE
Encoding problem with complex URLs in YUI fullpath

### ISSUE THREAD

**Issue by spsDrop** [YahooArchive/mojito#1257]
So I have a YUI config in my mojito config for vendor scripts mostly. It looks like this:

```
"yui":{
  "config":{
    "groups":{
      "vendor-scripts":{
        "modules":{
          "comscore-beacon":{
            "fullpath":"http://b.scorecardresearch.com/beacon.js"
          },
          "google-analytics":{
            "fullpath":"http://www.google-analytics.com/ga.js"
          },
          "quantcast":{
            "fullpath":"http://edge.quantserve.com/quant.js"
          },
          "chartbeat":{
            "fullpath":"http://static.chartbeat.com/js/chartbeat.js"
          },
          "buzzfeed":{
            "fullpath":"http://ct.buzzfeed.com/wd/UserWidget?u=xxxxx.com&to=1&or=vb&wid=1&cb=1332869026943"
          }
        }
      }
    }
  }
}
```

The buzzfeed url is parameterized and when it gets requested client side the url is like this:
http://ct.buzzfeed.com/wd/UserWidget?u=xxxxx.com\u0026to=1\u0026or=vb\u0026wid=1\u0026cb=1332869026943

I have also run this exact same url through YUI stand alone with out a problem.

**Comment by caridy** [comment]
mojito-next (0.9.x) uses the new serialization based on `express-state` pkg that should not mess with the encoding of the urls.
