### ISSUE TITLE
Update or remove Express

### ISSUE THREAD

**Issue by chetanankola** [YahooArchive/mojito#126]
I recently tried deploying my Mojito app to "Nodejitsu" and the folks at Nodejitsu told me that Express needs update since a "race condition bug for listening" (my app apparently wasnt listening right) was fixed in Express 2.5.9

So I was asked to wait till "Mojito" updates its express.

To deploy onto nodejitsu I was asked to make the following changes:

In my App's server.js I was asked to change this line:
module.exports = require('mojito').createServer();
to
module.exports = require('mojito').listen();

and in package.json
    "scripts": {
        "start": "mojito start"
    }

to 

  "scripts": {
    "start": "server.js"
  },

**Comment by rwaldura** [comment]
Thanks for the report, Chetan.
Guess we'll just have to upgrade Express!

**Comment by mojit0** [comment]
There are a couple of issues. Updating express is something we can schedule, but there's also some unfortunate cruft in the startup sequence that means the server.js file won't start mojito properly so changing from 'mojito start' to 'server.js' may not be workable. The good news is this is on our radar for the near-to-mid-term. We'll try to see if we can bump this up given that it's in your way tho!

**Comment by Marak** [comment]
Please let me know if there is anything I can do to help in making sure mojito apps can be required and started programmatically.

A top-level method to start up a server that accepts configuration options would be ideal.

**Comment by FabianFrank** [comment]
@mojit0 @Marak @rwaldura @chetanankola 

I just played with Mojito 0.3.28 and nodejitsu. After small changes (see referenced pull request) I got our weather training app working on nodejitsu:
http://fabianfrank.myweatherapp.jit.su/

You can find the source of the weather app (fixed package.json and server.js) here:
https://github.com/FabianFrank/trainingMojito/tree/master/lesson1/myWeatherApp

**Comment by rwaldura** [comment]
@mojit0 is working on this, via #422.

**Comment by rwaldura** [comment]
See also bz5753621 for an example of how Express is currently used -- i.e. we need to support the upload use-case even though we drop Express.

**Comment by rwaldura** [comment]
We've updated Express to 2.5.10. I'll open another ticket to chuck it out entirely (i.e. drop our dependency on Express).
