### ISSUE TITLE
[docs] customized contextualizer is needed to handle custome dimensions.

### ISSUE THREAD

**Issue by lzhan** [YahooArchive/mojito#1260]
It is better to document the following under:
http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_using_contexts.html

"If a property has its own dimensions.json (for custom dimensions) then it needs to provide its own contextualizing middleware (and use that instead of mojito's default contextualizing middleware)."

**Comment by caridy** [comment]
@lzhan can we close this? /cc @zhouyaoji
