### ISSUE TITLE
Documentation - Troubleshooting to be updated with message for identifying wrong dimension 

### ISSUE THREAD

**Issue by jithine** [YahooArchive/mojito#1287]
Currently if I use a new dimension, for example (environment:staging), mojito throws a weird message -  "Error: The settings group '{"environment":"staging"}' has already been added" - which is not useful in identifying the actual error. 
Requesting to either update the error message to me more meaningful or just add this to  the troubleshooting section at http://developer.yahoo.com/cocktails/mojito/docs/reference/mojito_troubleshooting.html

**Comment by lzhan** [comment]
Added a trello card in to do list.

**Comment by lzhan** [comment]
This is fixed in ycb release 1.1.0: https://github.com/yahoo/ycb/

**Comment by lzhan** [comment]
Related change is also made in mojito 0.8.1.
