### ISSUE TITLE
Incorrect documentation for arrow functional tests

### ISSUE THREAD

**Issue by jithine** [YahooArchive/mojito#1291]
Functional test example given at step 17 here, http://developer.yahoo.com/cocktails/mojito/docs/dashboard_tutorial/06_testing.html#creating-the-application is wrong. With the current example, arrow is unable to parse the test results. I am using arrow - 0.0.86

It needs to change to something similar to the following format. 

```
/*
 * Like other tests, this is a YUI test module
 *
 */
YUI.add("Quote-tests 2", function (Y) {

    //We initialize the suite object as a YUI test suite and with a suite title
    var suite = new Y.Test.Suite("Quote Page test of the test 2");

    suite.add(new Y.Test.Case({
        testQuote: function() {
            Y.Assert.areEqual("1", "1");
        }
    }));

    //Never "run" the tests, simply add them to the suite. Arrow takes care of running them
    Y.Test.Runner.add(suite);
}, "0.1", {requires:["test","node","node-event-simulate"]});
```

**Comment by lzhan** [comment]
Card is added in the todo list.

**Comment by zhouyaoji** [comment]
Hi Jithin,

The Arrow test code works, but the instructions for running the tests was missing a step for starting the Arrow server. I corrected the steps for running the Arrow tests and went through all the steps again and had no issue running the functional tests. I was using Arrow version 0.0.87. 

Thanks.
