### ISSUE TITLE
Mojito missing mkdirp dependency in build 0.8.0

### ISSUE THREAD

**Issue by elwayman02** [YahooArchive/mojito#1294]
The latest version of Mojito is unable to be installed successfully, giving the following error upon "npm i mojito":

889 error notarget No compatible version found: mkdirp@'>=0.4.0-0'
889 error notarget Valid install targets:
889 error notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5"]
889 error notarget
889 error notarget This is most likely not a problem with npm itself.
889 error notarget In most cases you or one of your dependencies are requesting
889 error notarget a package version that doesn't exist.
890 error System Windows_NT 6.1.7601
891 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "mojito"
892 error cwd C:\Projects\Signals\UI
893 error node -v v0.10.22
894 error npm -v 1.3.14
895 error code ETARGET

**Comment by lzhan** [comment]
This happens on Windows. Card is added in todo list.

**Comment by juandopazo** [comment]
Hi. I tested the last 3 releases and I could install and run them all on Windows 7 64-bits. There are some dependencies of Mojito that depend on `mkdirp`. Could it be that you had any of those installed globally? Can you still reproduce the issue? If so, can you create a gist with the whole log for the install?

**Comment by clarle** [comment]
I also haven't seen any `package.json` dependencies we have with `mkdirp@'>=4.0-0'`.

Windows_NT 6.1.7601 is Windows 7 SP1, so don't know. :/

**Comment by juandopazo** [comment]
Closing this issue until we can get a reproducible test case.
