### ISSUE TITLE
Request for mojito-cli creating templates using Promises

### ISSUE THREAD

**Issue by ItsAsbreuk** [YahooArchive/mojito#1302]
I would love to see mojito-cli generate Promises instead of callbacks.
So, the template for a model could be:

``` js
/*jslint anon:true, sloppy:true, nomen:true*/
YUI.add('FooModel', function(Y, NAME) {

/**
 * The FooModel module.
 *
 * @module Foo
 */

    /**
     * Constructor for the FooModel class.
     *
     * @class FooModel
     * @constructor
     */
    Y.namespace('mojito.models')[NAME] = {

        init: function(config) {
            this.config = config;
        },

        /**
         * Method that will be invoked by the mojit controller to obtain data.
         *
         * @method getData
         * @return {Promise}
         */
        getData: function() {
            return new Y.Promise(function (resolve, reject) {
                /*
                 * if error then:
                 *
                 * reject(new Error('reason'));
                 *
                 */
                 resolve({ some: 'data' });
            });
        }

    };

}, '0.0.1', {requires: ['promise']});
```

while the template for controller.server.js would be:

``` js
/*jslint anon:true, sloppy:true, nomen:true*/
YUI.add('Foo', function(Y, NAME) {

/**
 * The Foo module.
 *
 * @module Foo
 */

    /**
     * Constructor for the Controller class.
     *
     * @class Controller
     * @constructor
     */
    Y.namespace('mojito.controllers')[NAME] = {

        /**
         * Method corresponding to the 'index' action.
         *
         * @param ac {Object} The ActionContext that provides access
         *        to the Mojito API.
         */
        index: function(ac) {
            ac.models.get('model').getData().then(
                function(response) {
                    ac.assets.addCss('./index.css');
                    ac.done({
                        status: 'Mojito is working.',
                        data: response
                    });
                }
            ).then(
                null,
                Y.bind(ac.error, ac)
            );
        }

    };

}, '0.0.1', {requires: ['mojito', 'mojito-assets-addon', 'mojito-models-addon']});
```

Regards,
Marco.

**Comment by imalberto** [comment]
Taking into account that promises might not everybody's cup of tea, I would not make it the default and force it onto users. Perhaps a new archetype could be added that would use Promises instead of callbacks.

Users will have the choice to use either.

**Comment by ItsAsbreuk** [comment]
Yeah i agree that promises are difficult to start with. But that also accounts for Mojito itself. I see mojito as the leading edge framework of today/tomorow. So it wouldn't hurt to gentle push users into this direction. btw, personally i think the promise-code is easier to read than when using callbacks - but that is once you are familiair with them.

Giving users the choice is a good solution as well.

**Comment by caridy** [comment]
we have multiple archetypes, maybe we can add one with promises :)

**Comment by ItsAsbreuk** [comment]
It is not that i'm asking for it because it is 'just possible'.
The thing with promises is that they make it easy to chain or batch.

To illustrate this: i am using a custom module promise-based using node-mysql. Now I create mojito's models like this:

``` js
var dbConnection = new Y.DatabaseConnection({
    database: 'mydb',
    user: 'myusername',
    password: 'mypassword'
});

getUserId: function(username, password) {
    return dbConnection.queryPromise('select userid from users where (username=?) && (password=?)', [username, password]);
},

getOrders: function(userid) {
    return dbConnection.queryPromise('select * from orders where userid=?', userid);
},

getOrderDetails: function(orderid) {
    return dbConnection.queryPromise('select * from orderdetails where orderid=?', orderid);
}
```

imagine how easy this is to use when calling chained and batched data from within the controller. Previously I had to do this with callbacks which was a nightmare.

Creating another archetypes is an option, but to be honest: i didn't know they existed until now. so new users will still stick using callbacks. Just to reconsider.

**Comment by ItsAsbreuk** [comment]
for readers who are interested in the code-details:
https://gist.github.com/ItsAsbreuk/6778206
https://gist.github.com/ItsAsbreuk/7699934

**Comment by drewfish** [comment]
I'm also fond of promises.  The trick is that not all (server-side) javascript developers are even familiar with promises.  That's not to say that Mojito should cater to the _lowest_ common denominator, just that it should work well with the current/average skillset of the developer community.  The core value of Mojito is not that it's "a framework that uses the leading edge technologies" but instead that it is "a framework for developing large/complex applications using MVC".  Said another way, our mandate _isn't_ to present/promote leading edge technology/practices.

(Also, promises might be considered bleeding edge, as I've seen some promise libraries properly propagate errors, and/or have performance overhead from try/catch blocks.)

However, in Mojito we do have the archetypes as a way to easily use promises in your project.  Yeah, the documentation on how to setup and use archetypes is a bit lacking.

**Comment by drewfish** [comment]
BTW, I very often turn to the [async](https://npmjs.org/package/async) NPM package for managing callback-heavy algorithms.  It has a lot of methods but I mainly use `series()` and `parallel()` and occasionally `waterfall()`.

**Comment by caridy** [comment]
Alright, closing this in favor of customization per application thru archetypes.

**Comment by ItsAsbreuk** [comment]
All right, 
but just to let you know: inside almost every binder, i use this code:

``` js
        invokePromise: function(action, options) {
            var instance = this;
            return new Y.Promise(function (resolve, reject) {
                instance.mojitProxy.invoke(
                    action,
                    options,
                    function(err, data) {
                        err && reject(err);
                        resolve(data);
                    }
                );
            });
        },
```

which enables batching invoke-calls.
Marco

**Comment by caridy** [comment]
nice! that's probably the preferable way, without having to bring promises into the core.
