### ISSUE TITLE
Featurerequest: reviver-method for params.getFromBody-bodyparsing json stringified requests

### ISSUE THREAD

**Issue by ItsAsbreuk** [YahooArchive/mojito#1307]
I'm not sure if I get the title right, so let me explain:

When a client posts data of the contenttype 'application/json' the Mojito automaticly parse this into a hash. The problem is that the Date-type gets lost.

So, on the client side, I use Y.JSON.stringify(myobject), which will stringify Date-type into ISO-strings.

On the serverside, I would like Mojito to parse the request-data, using this reviver:

``` js
var DATEPATTERN = /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/,
      REVIVER = function(key, value) {
          return DATEPATTERN.test(value) ? new Date(value) : value;
      };
```

Currently, there is no way to tell Mojito doing this; express can. It would be nice if there was a way to do so. Personally, I think the reviver should be setup inside routes.json, for it might be needed to use diffferent revivers (or none) per route.

Regards,
Marco.

**Comment by caridy** [comment]
No no, this is a no-go in mojito. You have full control using express middleware in mojito to do whatever you want with those arguments before they get to mojito engine:

http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_extensions.html#middleware
