### ISSUE TITLE
request for MojitProxy.refreshView() not to reload css-assets

### ISSUE THREAD

**Issue by ItsAsbreuk** [YahooArchive/mojito#1312]
I have composite mojits that are refreshedViewed() multiple time with different childmojit configuration.

the css of this mastermojit is reloaded a huge amount of time now. It would be great if the css-assets wre not reloaded. Either by default, or as an option, like mojitProxy.refreshView({fetchCSS: false})

Best regards,
Marco.

**Comment by ItsAsbreuk** [comment]
where fetchCSS=false not applies to the childmojits that haven't been loaded yet - of coarse..

**Comment by drewfish** [comment]
I think mojito should be smart enough to not reload a CSS asset that has already been loaded on the page.

**Comment by ItsAsbreuk** [comment]
i agree. just keep in mind that we can do a refreshView with param-options where the param-options make the controller to serve different assets. so the logic should track css-files instead of mojits-actions.

**Comment by caridy** [comment]
@ItsAsbreuk, are you using `shaker`?

**Comment by ItsAsbreuk** [comment]
@caridy no not for these current projects
(i will activate shaker in a couple of week though)

**Comment by ItsAsbreuk** [comment]
Here is a screenshot of my system: 

http://projects.itsasbreuk.nl/screenshot.jpg

In the jpg-image you see in the inspector that index.css is loaded twice.
(which i can confirm when inspecting the actual html)

**Comment by caridy** [comment]
alright, let's get this fixed. @ItsAsbreuk if you can provide a very basic repro case, that will be awesome.

/cc @lzhan can you investigate more about this?

**Comment by ItsAsbreuk** [comment]
Yeah sure
I can build a repo this weekend.
Let you know.

**Comment by lzhan** [comment]
@caridy @ItsAsbreuk I will work on it.

**Comment by lzhan** [comment]
@ItsAsbreuk @caridy I can reproduce this with our existing test app.

**Comment by caridy** [comment]
@lzhan was this fixed?

**Comment by lzhan** [comment]
The pull request with solution is closed. Long term solution needs to be discussed.

**Comment by caridy** [comment]
Ok, I will close this one, and you can open a new issue for the long term solution.
