### ISSUE TITLE
escape comboBase will cause some combo handler stop working

### ISSUE THREAD

**Issue by jianglibo** [YahooArchive/mojito#1318]
this is comboBase: 

```
http://yuimin.fh.gov.cn/min/b=3.12.0/build&130727&f=
```

this is mojito deploy generated code:

```
YUI.applyConfig({"base":"http://yuimin.fh.gov.cn/3.12.0/build/","comboBase":"http://yuimin.fh.gov.cn/min/b=3.12.0/build\\u0026130727\\u0026f=","comboSep":",","root":"","fetchCSS":true,"combine":true,"debug":true,"logLevel":"warn","logLevelOrder":["debug","mojito","info","warn","error","none"],"lang":"zh-CN","groups":{"app":{"combine":true,"maxURLLength":1024,"base":"/static/","comboBase":"/combo~","comboSep":"~","root":"/static/"}}});
```

surely combo hanlder will stop working.

**Comment by caridy** [comment]
@jianglibo it will take a while to fix this one. Once we release mojito-next (few next week), we should be able to replace the piece that does the serialization with the brand new `express-state`. I will keep you posted!

**Comment by jianglibo** [comment]
thank you for amazing mojito framework

**Comment by caridy** [comment]
mojito-next (0.9) solves this issue by using `express-state` serialization routine.
