### ISSUE TITLE
Tunnel client timeout is hardcoded to 10 seconds

### ISSUE THREAD

**Issue by rmadhuram** [YahooArchive/mojito#135]
https://github.com/yahoo/mojito/blob/master/source/lib/app/autoload/tunnel.client-optional.js

The tunnel client timeout is hardcoded to 10 seconds, and causes some use cases to time out. It should instead be configurable via appConfig.

**Comment by rwaldura** [comment]
Sweet! Thanks for the patch!

**Comment by rwaldura** [comment]
Oh wait. Could you submit a patch please?

**Comment by rmadhuram** [comment]
Hi Ren,

I'll submit one soon. It should be a one line fix, but testing the fix would suck up lot of my time. I'll get to it as soon as I get some time.

Regards,
Raj

**Comment by rwaldura** [comment]
Very kind of you, thanks.
Whoever gets to it first then!
Thanks again for reporting the issue.

**Comment by rmadhuram** [comment]
Here is the patch:

``` javascript
diff --git a/source/lib/app/autoload/tunnel.client-optional.js b/source/lib/app/
index 7117671..19f4e9a 100644
--- a/source/lib/app/autoload/tunnel.client-optional.js
+++ b/source/lib/app/autoload/tunnel.client-optional.js
@@ -30,7 +30,7 @@ YUI.add('mojito-tunnel-client', function(Y, NAME) {
                 },

                 getProxyTimeout: function() {
-                    return 10000;
+                    return appConfig.tunnelTimeout || 30000;
                 }
             };
```

I tested it by modifying the inter-mojit example and verified it works.
Please note that I bumped up the default timeout to 30 seconds. Applications can override by setting the "tunnelTimeout" property in application.json

Regards,
Raj

**Comment by mridgway** [comment]
#170 also addresses this issue. With either of these patches, I still don't think you can do proper error handling for time outs. I think there is a bigger issue inside Dali in how timeouts are handled. It doesn't seem to propagate back up the Dali stack to the tunnel client when the RPC call times out. With #170 it would be much easier to handle error cases (and I plan on doing subsequent pull requests for it if it is accepted).

**Comment by rmadhuram** [comment]
Sounds good.

**Comment by zhouyaoji** [comment]
Just to clarify for the documentation, the value for "tunnelTimeout" is a number (not a string) and is in milliseconds as shown in the example 'application.json' below, correct?

[
    {
        "settings": ["master"],
         ...
        "tunnelTimeout": 5000,
        "specs": {
            ...
        }
    }
]

**Comment by rwaldura** [comment]
see also #345, #359.
