### ISSUE TITLE
For some reason I have obtained this issue when i run mojito on windows

### ISSUE THREAD

**Issue by houyhnhnm** [YahooArchive/mojito#1369]
I started a new project and created my mojito app and a mojit for it.  But, when I started mojito
mojito start
I received these lines. I have other mojito apps that are running perfectly, but for this new app I dont know why it occurs. 
i am running mojito on windows 7. I know some new changes have been made. I dont think they matter because the other mojito apps are running as they should. But, here was the results of mojito start on a new app, with no modification by me in the day of this issue creation.

info: (mojito-resource-store): Store initialized
err!  Couldn't load lib/mojito.js

**Comment by aljimenez** [comment]
Hello. Which version of mojito is your application using? Mojito 0.9 starts differently from previous versions (see https://github.com/yahoo/mojito/wiki#mojito-v09).

**Comment by houyhnhnm** [comment]
thanks Albert. I already updated to mojito 0.9:) but the link was excellent to covering the changes. I had become too accustomed to the way things were.
