### ISSUE TITLE
Routes exposed to the client

### ISSUE THREAD

**Issue by aljimenez** [YahooArchive/mojito#1381]
Now that routes.json is no longer contextualized, there is no way to specify which routes can be made available to the client runtime. As a result all routes are visible on the client side, which adds to the size of the page and exposes internals.

**Comment by caridy** [comment]
This is supported thru `express-annotations`: https://github.com/yahoo/express-annotations#appfindallannotations

You can add specific marks into each route, (e.g.: `client: true`), then expose the result of the `app.findAll()` operation overruling the mojito default behavior, which is expose everything.

**Comment by aljimenez** [comment]
See this [pull request](https://github.com/yahoo/mojito/pull/1386)
