### ISSUE TITLE
Load custom template view in ac.composite.execute 

### ISSUE THREAD

**Issue by muhilvarnan** [YahooArchive/mojito#1388]
Hi,

   I need  clarification regarding the implementation of dynamic mojit (composite execute). I have two page namely "homepage" and "login". I planned to load the corresponding mojits of each page using a common controller by creating a mojit called "pagelayout". 

 Pagelayout mojit has following file structure :- 
      controller.server.js
      views/
            index.hb.html
            login.hb.html
     model....... etc

I have used ac.composite.execute command to load mojits dynamically. but i need to change the view based on the page request. (i.e) '/' -> index.hb.html and '/login' -> login.hb.html 

I know with ac.done(data,{view: {"name":"index"}}) we can achieve this feature. whether similar functianlity can be done with ac.composite.execute.

similat to below snippet(ac.composite.done) :- 

```
YUI.add('parent', function(Y, NAME) {
  Y.namespace('mojito.controllers')[NAME] = {
    index: function(ac) {
      ac.composite.done({ parent_data: 'Welcome'}, { "view": { "name": "page" }});
    }
  };
}, '0.1.0', {requires: ['mojito', 'mojito-composite-addon']});
```

changing of view template for ac.composite.execute?????

**Comment by caridy** [comment]
what version of mojito are u using? latest versions should support that as described here:
https://github.com/yahoo/mojito/pull/950

**Comment by muhilvarnan** [comment]
Version which i am using :- mojito-cli v0.2.0

if its in lastest version means, could u show how to do the above functionality with a small code snippet(controller file part alone),

Thanks for the reply ......

**Comment by muhilvarnan** [comment]
I have gone through the mojto docs and i finally came up this solution. It works fine for me: 

   ac.composite.execute(cfg,function(data, meta)
        {
         template ={ "name": "login" };
         meta['view']=template
          ac.done(data,meta);
     });
