### ISSUE TITLE
[bz5439377] configuration accepts neither null nor false values

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#14]
configuration currently does not accept false or null values as stated on json.org

**Comment by rwaldura** [comment]
mmmh thought we had fixed this...

**Comment by isao** [comment]
yes this fix landed in 0.3.10, see b49e45c007d60997eb7ffe139d6eb952eee7feb4 and ff69faf27fbc5a44126d50f88d4af15d38997601
