### ISSUE TITLE
Creating documentation

### ISSUE THREAD

**Issue by Satyam** [YahooArchive/mojito#148]
a) binders are not included (I haven't tried autoload modules)

b) The template for a controller states its class as Controller so there is a bunch of them listed in the API Classes index.  In fact controllers are saved under the name of the mojit so the template could use that or call it {Mojit}Controller, just as it does with the models, at least for the documentation

c) what would happen when there are controllers for more than one affinity?  The public interfaces would be expected to be the same (more or less), but private methods within it might not.

**Comment by zhouyaoji** [comment]
Hi Satyam,

You can find documentation for binders at the following URL: http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_binders.html

I'm not sure I completely understand item 'b)' in the issue that you filed. When you say templates, are you talking about 'archetypes' that are used to generate the mojit files (i.e., https://github.com/yahoo/mojito/tree/develop/source/lib/archetypes/mojit)? If so, please see the Creating Code from Archetypes (http://developer.yahoo.com/cocktails/mojito/docs/reference/mojito_cmdline.html#creating-code-from-archetypes).

As for 'c)', I am not aware that private controller methods are inherently different when they are run on the client or server, but obviously the runtime environments are different, so private methods on the server could, for instance, could access Node modules, whereas private methods on the client could access the DOM. I will confirm that there are any other differences for you as well. 

The reStructuredText source files for the Mojito documentation on YDN (see directory at http://developer.yahoo.com/cocktails/mojito/docs/) is also on GitHub (https://github.com/yahoo/mojito/tree/develop/docs/dev_guide), so you can add docs or make changes and then make a pull request.

Please let me know if you need more documentation for 'a)' and 'b)', and I will get back to you about item 'c)'. 

Thanks for your feedback and for filing this issue.

**Comment by Satyam** [comment]
a) I wasn't asking about client documentation, I am reporting that when mojito documents an application, it does not document the binders.

b) Yes, I was referring to archetypes, sorry.  I know where they are and I know I can change them but I am reporting this so that the standard version is already fixed.

c) ok, thanks

**Comment by zhouyaoji** [comment]
a) I see, you're talking about the 'mojito doc' command not generating documentation for binders. I'll file a enhancement ticket for this. Thanks!

b) We've made several changes to the archetypes over the past couple of weeks that you should see in the near future. If you notice that there is a bug or an issue that you can identify clearly and in detail, please file a bug or make a pull request.

c) Yes, I have confirmed with the Mojito team and private controller methods should work the same on the client and server. The only caveat is what I mentioned earlier--if you're using Node.js modules, you won't have access to that on the client or if you're accessing the DOM, you won't have access to that on the server.

Thanks, Satyam!

~Joe

**Comment by zhouyaoji** [comment]
Hi Satyam,

I went ahead and tested 'mojito docs' to see if it generated docs for binders, and it does.

After you write a new binder function, you would do the following:
1. Add YUIDoc comment blocks for your new function. See http://yui.github.com/yuidoc/syntax/index.html#primary-tags as a reference.
2. From your application directory, run the following:
   $ mojito docs mojit {mojit_name}
3. Go to the doc URL outputted by Mojito.
4. You should see the documentation for your new function.

Let me know if this helps. Thanks.
