### ISSUE TITLE
"location" doesn't work with a package "type":"mojit"

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#155]
According to http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_npm.html when I make an NPM package that contains a single mojit (`"type":"mojit"`) I should be able to use `"location"` to specify a location for my mojit.  However, that doesn't work.  The mojit ends up with the wrong name, the `basename()` of `"location"` instead of the `"name"` specified in the `package.json`.

**Comment by caridy** [comment]
@drewfish is this still an issue?

**Comment by drewfish** [comment]
This was fixed in commit 4ff4d43.
