### ISSUE TITLE
[bz5309856] Support custom middleware as part of the Mojito configuration process. 

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#16]
Allow applications to define custom middleware components which will execute in the Express/Connect middleware stack. The actionContext and other Mojito components must be verified for correctness upon completion of all middleware component execution, prior to the final request handling steps.

**Comment by mridgway** [comment]
This should be supported already. I'm not entirely sure about the validation of AC and other such components, but we should file individual bugs for components that need validation.

We also discussed refactoring this to remove the BC condition and clean up the code.

**Comment by caridy** [comment]
/ping @imalberto, let's keep this around just for reference until we land the 0.6 refacfor where they will be able to control middleware thru express directly.

**Comment by caridy** [comment]
this is done in mojito-next (0.9), where middleware are just express/connect middleware.
