### ISSUE TITLE
[bz4591526] Add ability to specify a different binder from the view default

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#18]
In addition to being able to specify a different view template from the default (the action name), we'd like to be able to specify a different binder as well, in the case where we'd like to share a view template between two different actions, but with different bindings.

**Comment by caridy** [comment]
ops, I didn't notice this open issue before making the pull request. Anyway, here is the pull:

https://github.com/yahoo/mojito/pull/182

**Comment by caridy** [comment]
This is now solved for ac.done and ac.composite.done as well.
