### ISSUE TITLE
linking to a different mojito action should not reload page

### ISSUE THREAD

**Issue by trungpham** [YahooArchive/mojito#183]
if mojito is deployed to the client, then clicking on a hyper link that points to another action should not cause the entire page to reload.

**Comment by rwaldura** [comment]
I guess I don't understand: what prevents you from binding this link to an event handler?

**Comment by caridy** [comment]
This is one of the primary use-cases in mojito, and it should work. Can you provide more details @trungpham? repro case maybe?

**Comment by caridy** [comment]
closing old tickets.
