### ISSUE TITLE
Access to databases

### ISSUE THREAD

**Issue by juzerali** [YahooArchive/mojito#185]
I couldn't find any documentation on how to use and integrate a database on mojito. Can you link me to any related doc?

**Comment by isao** [comment]
Hi Juzer. The docs describe using YQL (you can define your own tables, and CRUD operations are supported) as a web-service interface.

There's nothing about using redis/mysql/postgres/etc specific to mojito yet. To use these you can do it the simple node.js way, in your server-affinity controllers, models, add-ons, or middleware.

If that's unfamiliar, you might want to ask the kind folks at https://groups.google.com/forum/?fromgroups#!forum/nodejs or #node.js on freenode.
