### ISSUE TITLE
[bz4645306] HTMLFrameMojit doesn't allow printing error message

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#20]
When I wrap a Mojit in HTMLFrameMojit and I use ac.error() in a controller.server.js file, nothing is printed since, this.done('') is empty. Shouldn't there be a way to print the error message?

**Comment by caridy** [comment]
This is related with the composite error handling, issue #25. Once we get that fix, FrameMojit will catch the error and potentially propagated through ac.error which couse the proper error report in the browser.

**Comment by caridy** [comment]
You can now create your own frame mojit and control errors in the `child`, or you can rely on the express middleware to manage the errors.
