### ISSUE TITLE
Tests that ran under 0.3.26 no longer run under 0.3.27

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#215]
(Reported by Adam)

When I run my tests under 0.3.26 I get:
...

✔  passed    ProgrammerMojit-tests :: ProgrammerMojit :: should display all programmers
✔  passed    ProgrammerMojit-tests :: ProgrammerMojit :: should display programmer names and languages
✔  passed    ManagerMojit-tests :: ManagerMojit :: should display all managers
✔  passed    ManagerMojit-tests :: ManagerMojit :: should display manager names and handicaps
✔  passed    EmployeeListingMojit-tests :: EmployeeListingMojit :: should delegate to composite addon

Total tests: 5    ✔ Passed: 5    ⚑ Deferred: 0    ✖ Failed: 0    100% pass rate

But since updating to 0.3.27 I get this instead:
...

warn: (yui): NOT loaded: ProgrammerMojit-tests
warn: (yui): NOT loaded: ProgrammerMojit-tests
warn: (yui): NOT loaded: ManagerMojit-tests

I noticed that the version of YUI Test also bumped, but I couldn't find anything over there or here to tell me what I might need to change. Any ideas?

P.S. the test code was written by following the current docs. Here's one of the tests that used to pass but no longer loads:

YUI.add('ManagerMojit-tests', function(Y) {

```
var suite = new YUITest.TestSuite('ManagerMojit-tests'),
    controller = null,
    doneResults = null,
    A = YUITest.Assert;

suite.add(new YUITest.TestCase({

    name: 'ManagerMojit',

    setUp: function() {
        controller = Y.mojito.controllers.ManagerMojit;
        controller.index({
            done: function(data) {
                doneResults = data;
            }
        });
    },
    tearDown: function() {
        controller = null;
    },

    'should display all managers': function() {
        A.areSame("Managers", doneResults.title);
        A.areSame(2, doneResults.managers.length);
    },

    'should display manager names and handicaps': function() {
        var george = doneResults.managers[0];
        A.areSame("George", george.name);
        A.areSame(2.5, george.handicap);

        var joe = doneResults.managers[1];
        A.areSame("Joe", joe.name);
        A.areSame(10, joe.handicap);
    }

}));

YUITest.TestRunner.add(suite);
```

}, '0.0.1', {requires: ['mojito-test', 'ManagerMojit']});

**Comment by mojit0** [comment]
https://github.com/yahoo/mojito/pull/232 merged and ready to push with next release fixes this.
