### ISSUE TITLE
Mu.Parser.parseText doesn't parse CR+LF newlines correctly

### ISSUE THREAD

**Issue by itsnotvalid** [YahooArchive/mojito#227]
Just out of some wrong git settings I checked out mojito using Github for Windows which apparently didn't obey my git global config settings. The reason why I need to check out and install mojito is because yuitest was marked [darwin, linux] in 0.7.3 which npm version of mijito depends on.
So what happened is that `Mu.Parser.parseText()` only split on '\n' but would strip out the \n out of \r\n in files with DOS line endings, which gives `SyntaxError: Unexpected token ILLEGAL` (which happened when I run `mojito create app` because my package.json.mu is also in DOS line endings!)
Quick fix: change '\n' to `/\r\n|\r|\n/`in source/lib/app/libs/Mulib/mu/parser.js

**Comment by mridgway** [comment]
Closing as "won't fix". We are migrating away from Mu entirely and recommend using Handlebars.
