### ISSUE TITLE
Suggested patch for ac.done

### ISSUE THREAD

**Issue by Satyam** [YahooArchive/mojito#229]
See:

https://gist.github.com/2828145

and some explanation in this conversation:

http://developer.yahoo.com/forum/Yahoo-Mojito/ac-composite-done-doesn-39-t-allow-for-data/1338186490048-64468bb1-0cfb-46b4-a9c8-8f62cf05299e

And an example:

https://gist.github.com/2828156

**Comment by caridy** [comment]
This was solved a while ago when ac.done() and ac.composite.done() become equivalents in term of api. Check `HISTORY.md` for more details.
