### ISSUE TITLE
Support for dynamic title in HTMLFrameMojit

### ISSUE THREAD

**Issue by devsathish** [YahooArchive/mojito#230]
Currently HTMLFrameMojit supports static title only (using application.json). Its a very basic use case and it has to supported at the platform level.
There is a workaround to set title using JS., But its not the right way since its not SEO compatible. Also, customizing HTMLFrameMojit / ShakerHTMLFrameMojit is not a good idea.

The fix is already available., Pls refer to this pull request: https://github.com/yahoo/mojito/pull/123

**Comment by rwaldura** [comment]
See pull request #123.

**Comment by devsathish** [comment]
Its just a change of two lines.
Replace HTMLFrameMojit:controller.server.js:76 with the following.

//Set the title (with fallback to default title)
var title = (meta.common && meta.common.title)?meta.common.title:'';
data.title = title || ac.config.get('title') || 'Powered by Mojito ' + Y.mojito.version;

I don't have the diff file. Hence giving the change in this comment.

**Comment by rwaldura** [comment]
Thanks for the patch. It does appear very simple indeed. We've been wanting to address this area (frame configuration) comprehensively, but maybe it's time for a quick fix.

We'll look at this in Sprint 38 starting July 16 and ending 2 weeks hence, thanks!

**Comment by haisuby** [comment]
is this patch available in the current version? I couldn't see any changes for this title issue. rwaldura@, could you please confirm the inclusion of this patch in the recent version? Thanks!

**Comment by caridy** [comment]
Closing this now that we have the infrastructure to facilitate the creating of new frame mojits, which is what we want people to do.
