### ISSUE TITLE
Mojito fails to start using node v0.8.0 because Mulib has a deprecated require('sys')

### ISSUE THREAD

**Issue by FabianFrank** [YahooArchive/mojito#231]
The problem is in line 1:
https://github.com/yahoo/mojito/blob/develop/source/lib/app/libs/Mulib/mu/compiler.js

$ node_modules/.bin/mojito start --context "environment:localhost"
path.existsSync is now called `fs.existsSync`.

sys.js:1
throw new Error(
      ^
Error: The "sys" module is now called "util".
    at sys.js:1:69
    at NativeModule.compile (node.js:602:5)
    at Function.NativeModule.require (node.js:570:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/frankfa/Yahoo/src/searchfe/mojito/sd/node_modules/mojito/lib/app/libs/Mulib/mu/compiler.js:1:73)

**Comment by mojit0** [comment]
Fixed by https://github.com/yahoo/mojito/pull/228 which should be merged shortly :)

**Comment by mojit0** [comment]
Oops. Hate it when that happens. Wrong issue :)

**Comment by rwaldura** [comment]
Fabian:
Can we safely close this in favor of pull request #228?

**Comment by FabianFrank** [comment]
@rwaldura yes, I reviewed the pull request and it will fix this one.

**Comment by rwaldura** [comment]
OK
Whoever merges pull request #228, please close this issue at the same time.

**Comment by mojit0** [comment]
OK, but I'm going to have to close and redo that pull request. It's a mess. Full of unrelated commits.

**Comment by isao** [comment]
it's pull #233 not 228 now

however, for some (probably unrelated) reason, it fails mojito-github-pull (job 22)
