### ISSUE TITLE
mojito-handler-tunnel and DaliProxy mojit are not honoring the runtime:server 

### ISSUE THREAD

**Issue by caridy** [YahooArchive/mojito#236]
When making a tunnel request, the body.reqs[0].data.context will be produced at the client side based on mojitProxy.context, this of course has runtime=client. Once this context obj lands on the server side as part of the tunnel request, it is processed by mojito-handler-tunnel to produce the "command" structure used to _dispatch the mojit action. The problem is that "runtime" is not overruled (even though it was forced during a previous middleware entity.

As a result, if you have any settings like this in your application.json:

{
    "settings": [ "runtime:server" ],
    "foo": "bar"
}

ac.app.config.foo will be "bar" only when hitting a traditional controller/action through a route, but it will not be honored during a tunnel request to any of the mojits, because for the tunnel, runtime will be "client".

As today, we solved this by hacking into the DaliProxy, and doing this in the controller:

110               proxyCommand.context.runtime = 'server';    //// <---- this is our hack!
111 
112             // dispatch the command as the proxy
113             ac._dispatch(proxyCommand, makeAdapter(ac, txId));

so, the mojit that will be executed will honor the runtime accordingly.

I don't think this is the right thing to do, I think mojito-handler-tunnel should take care of this before producing the final "command" structure.

Please, let me know if all this makes any sense, so I can do a proper pull request if needed.

**Comment by mojit0** [comment]
Dali will be leaving Mojito although we're not sure about timing. There's a pull request we haven't had a chance to fully vet which replaces Dali with Socket.io which I believe will mean any patch of this type will need to be done on that new infrastructure. In the interim I'd say go ahead and create a pull request and we'll prioritize how we want to get both things accomplished.

ss

**Comment by drewfish** [comment]
@caridy:  I agree with your assessment.  The fixup should be done in the mojito-handler-tunnel middleware.

@mojit0:  The "DaliProxy" mojit is just a proxy mojit -- it has very little to do with Dali.  It's used as the proxy mojit by the mojito-handler-tunnel middleware.

**Comment by FabianFrank** [comment]
I tried to address this issue with a pull request. This fix works fine in our app.

**Comment by caridy** [comment]
Perfect, thanks for the pull request @Schnitz. Now we just need the test!

**Comment by FabianFrank** [comment]
@caridy A test has been provided in the pull request. Thanks.

**Comment by mridgway** [comment]
Fixed by https://github.com/yahoo/mojito/pull/242
