### ISSUE TITLE
mojito test app . crashes on skeleton app due to missing dom in binder test with common affinity

### ISSUE THREAD

**Issue by FabianFrank** [YahooArchive/mojito#239]
Now that the DOM dependency has been removed from YUI, testing binders on the server side is a bit more complex. Today what happens is:

frankfa@knowenter-lm:~/tmp (0) $ ~/github/mojito/source/bin/mojito create app testapp
creating app called 'testapp'
(using "default" archetype)
✔ app: testapp created!
frankfa@knowenter-lm:~/tmp (0) $ cd testapp/
frankfa@knowenter-lm:~/tmp/testapp (0) $ ~/github/mojito/source/bin/mojito create mojit testmojit
creating mojit called 'testmojit'
(using "default" archetype)
✔ mojit: testmojit created!
✔ mojito done.
frankfa@knowenter-lm:~/tmp/testapp (0) $ ~/github/mojito/source/bin/mojito test app .
[warn] undefined: overriding application config value: env
[info] MojitoServer: ALREADY EXISTS: asset favicon.ico -- in mojit shared -- using from pkg testapp@0.0.1 -- skipping from pkg mojito@0.3.27
[WARN] MojitoServer: your mojit "testmojit" has a server affinity and these client-related deps: node-base, node-core, dom-core, dom-base, node-event, node-pluginhost, node-screen, dom-screen, dom-style, dom-style, node-style
[WARN] MojitoServer: Mojito may be unable to start, unless you have provided server-side DOM/host-object suppport
warn: (mojito-perf): microtime not found. Recorded times will not have microsecond accuracy
warn: (mojito-perf): microtime not found. Recorded times will not have microsecond accuracy
warn: (yui): NOT loaded: mojito-client

/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:1147
            throw (e || new Error(msg));
                        ^
TypeError: Cannot read property 'documentElement' of null
    at Object.fn (/Users/frankfa/github/mojito/source/node_modules/yui/dom-base/dom-base-min.js:7:50)
    at [object Object]._attach (/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:701:33)
    at /Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:962:31
    at [object Object]._notify (/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:836:17)
    at [object Object].<anonymous> (/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:971:27)
    at Object._finish (/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:6432:19)
    at Object._onSuccess (/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:6477:14)
    at /Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:6674:24
    at Object._insert (/Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:6683:13)
    at /Users/frankfa/github/mojito/source/node_modules/yui/yui-nodejs/yui-nodejs.js:6771:18

This is because the sekelton binder test has common affinity, but requires the DOM to run. I think there are at least 2 possible solutions:
1. change the affinity to client
2. depend the mojito framework on jsdom and inject the jsdom dependency into YUI when running UTs. (http://yuilibrary.com/yui/docs/yui/nodejs-dom.html)

I think that 2. is the better option, because I really like to be able to run all my UTs using mojito test. Obviously this is not a must have, but a very nice convenience feature. What do you think? Let me know if you agree or have something else in mind, so I can provide a pull request.

**Comment by chqlb** [comment]
Is this bug fixed @mridgway ? I encounter this problem with mojito 0.4.2.

**Comment by mridgway** [comment]
@chqla Yes, it should be fixed in 0.4.3 by PR #394.

**Comment by mridgway** [comment]
Sorry, #395.

**Comment by chqlb** [comment]
thanks  @mridgway,

**Comment by rwaldura** [comment]
see also https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_3

**Comment by nottoseethesun** [comment]
I have Mojito 0.4.3 and still see this exact issue.

**Comment by chqlb** [comment]
This issue is caused by jsdom not supported in mojito anymore.

The affinity of binder tests should be client. So, you need to rename the binder tests
file from index.common-tests.js to index.client-tests.js

**Comment by nottoseethesun** [comment]
Thank you.  I had tried that and it works.  But I am not sure why.

I see that we have a dependency on a model declared with 'client' affinity.  It uses 'Y.mojito.lib.REST.POST'.  But does that have a dom dependency?  It seems that 'REST' lib code should work on the server, since it's of 'common' affinity: './tests/unit/lib/app/autoload/test-rest.common.js'    

So I tried renaming the client-side model to have 'server' affinity, but get:

AlertModalMojit-tests :: AlertModalMojit user tests :: test mojit
Values should be the same.
Expected: Mojito is working. (string)
Actual: undefined (undefined)

Eventually, we'll want to move our controllers to the server side, and will need to get tests for server-side mojits to work.

**Comment by nottoseethesun** [comment]
We actually found that running the 'app' test with the affinities all set to 'client' had the same result as deleting all the 'test' dirs in the mojit dirs: It's an empty result, which is different than success, which I had thought we had.

**Comment by FabianFrank** [comment]
mojito test only executes tests with common or server affinity. If you want client-side UTs to run with mojito test you have to give them common affinity and then ensure that the DOM is available when the tests are running:
http://yuilibrary.com/yui/docs/yui/nodejs-dom.html
