### ISSUE TITLE
Structured Extensions (Plugins)

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#24]
Mojito needs a way to group various bits of code that -- when combined -- provide additional features to the platform. These extensions should be installable via npm, but should not be applied to all Mojito applications when installed. Mojito apps should identify which extensions they require within their configuration.

Dependencies:

The npm package for an extension should identify any dependencies on other Mojito extensions. At the application level, a requirement for one extension should automatically install any dependent extensions within that application.

**Comment by drewfish** [comment]
This was completed a while ago.
