### ISSUE TITLE
mojito test app . produces a test failure due to an error in the archetype test

### ISSUE THREAD

**Issue by dmitris** [YahooArchive/mojito#255]
Following the "Getting Started" tutorial http://developer.yahoo.com/cocktails/mojito/docs/getting_started/mojito_getting_started_tutorial.html#make-the-sample-mojit
and creating a simple mojit as instructed, I'm getting a test failure when running "mojito test app ." :

```
Test Results:
artifacts/test/result.xml


✔  passed HelloMojitModelFoo-tests :: HelloMojitModelFoo user tests :: test mojit model
⚑ deferred    HelloMojitBinderIndex-tests :: HelloMojit index binder tests :: TODO: test update id
✖  FAILED HelloMojit-tests :: HelloMojit user tests :: test mojit

FAILURE DETAILS:
================
HelloMojit-tests :: HelloMojit user tests :: test mojit
Values should be the same.
Expected: {"x":"y"} (string)
Actual: [object Object] (object)


Total tests: 3  ✔ Passed: 1   ⚑ Deferred: 1 ✖ Failed: 1   33% pass rate
```

I'm running it on Mac Lion and the mojito's version is 0.3.26

This happens due to this line in source/lib/archetypes/mojit/default/tests/controller.server-tests.js
https://github.com/yahoo/mojito/blob/develop/source/lib/archetypes/mojit/default/tests/controller.server-tests.js.mu#L52

since modelData and doneResults.data are now objects (see https://github.com/yahoo/mojito/blob/develop/source/lib/archetypes/mojit/default/tests/controller.server-tests.js.mu#L27), they are not equal even if they have the same keys and values.

I made a fix - https://github.com/dmitris/mojito/commit/b6b646f87cb001daa77b11fe7d503485fc5add46
removing the offending line and adding instead:
     A.isObject(doneResults.data);
     A.isTrue(doneResults.data.hasOwnProperty('x'));
     A.areEqual('y', doneResults.data['x']);

with this change, the tests pass cleanly.  Feel free to merge.  Thanks.

**Comment by mridgway** [comment]
This is now fixed.
