### ISSUE TITLE
[v1 B-55826] Mojito "view" becomes Mojito "template"

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#257]
The mojito concept of "view" should become "template" instead, to be consistent with YAF.  This is perhaps nothing more than a terminology change (no architectural changes, though perhaps some filepath changes).

**Comment by trungpham** [comment]
yay

**Comment by rwaldura** [comment]
See also http://yuilibrary.com/projects/yui3/report/132 for the YAF side of things.

**Comment by caridy** [comment]
closing old tickets.
