### ISSUE TITLE
[v1 B-55827] Mojito "binder" converges to Y.Binder  

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#258]
Mojito's idea of a binder should align closely with YAF's idea of a binder.  This might even go so far as to throw away Mojito's binders and use Y.Binder instead.

(The goal is that an app built using YAF can migrate easily/naturally into a mojito app.)

**Comment by focuzz8** [comment]
I'm sorry... What is Y.Binder?

**Comment by drewfish** [comment]
Hehe.... just as Mojito is trying to learn some things from YUI App Framework, it is trying to learn some things from Mojito.  The two teams are working together.  It's still just a bunch of ideas -- nothing is final yet.

**Comment by caridy** [comment]
closing old tickets.
