### ISSUE TITLE
Binder don't work in some examples (but it seems like should)

### ISSUE THREAD

**Issue by focuzz8** [YahooArchive/mojito#263]
In mojito/examples/simple/part[4-8] binders don't work. Function to handle clicks was writter, but not attached to elements

**Comment by rwaldura** [comment]
@zhouyaoji Joe can you help?
Seems like oversight.

**Comment by zhouyaoji** [comment]
The 'simple' examples are not part of the documentation. The examples for the documentation are all in 'examples/developer-guide'. Because it's not a doc issue, I'm going to relabel the issue.

**Comment by caridy** [comment]
@zhouyaoji can we close this?

**Comment by zhouyaoji** [comment]
For the following examples, you have to go to URL http://localhost:8666/myBase/index to execute the mojit instance of type HTMLFrameMojit, which will deploy the binder code to the client. This information is in the file readme.md of each example.
- simple/part3
- simple/part4
- simple/part5

My guess is that focuzz went directly to http://localhost:8666, which would only render the child mojit instance and not deploy the binders to the client.
