### ISSUE TITLE
js files with same filename under different folders within 'node_modules' not being loaded

### ISSUE THREAD

**Issue by justineqian** [YahooArchive/mojito#266]
We have a couple of resources (YUI modules) which are meant to be shared across different mojito apps and are used by both server and client side execution. These resources are packaged separately. They both live in /node_modules directory within the mojito app after installation. For example:

Myapp/node_modules/myresource1/autoload/myfile.js
                                         /myresource2/autoload/myfile.js

The .js files of these resources have the same names, when the app is running, only one of the resource’s js file gets loaded on the client side. 

<script type=”text/javascript” src=”/static/autoload/myfile.js”></script>

If I changed the filename or the path, making them differently

Myapp/node_modules/myresource1/autoload/js/myfile.js
                                         /myresource2/autoload/myfile.js

, then both are loaded fine on client side.

**Comment by rwaldura** [comment]
@jqianyahoo what version of Mojito is this?
I venture this has been fixed by the new resource store released in 0.4.0
let us know, thanks!
