### ISSUE TITLE
mustache error crashes node

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#27]
In a model, I convert an object of objects to an array of objects like this:

var list = [];
list = Y.Object.values(this.feeds).sort(sortFeeds);

In the controller, I assign this array to an object and pass to ac.done() like
this:

var vudata = { //mustache template data
spaceid: this.config.spaceid,
tiles: []
};

//later
vudata.tiles = list;
ac.done(vudata);

Starting mojito and requesting the page crashes node

**Comment by isao** [comment]
fixed with f384f71583be578bb7c46c9f31021dfbaf492c36 and pull and f384f71583be578bb7c46c9f31021dfbaf492c36
