### ISSUE TITLE
Custom HTTP status message

### ISSUE THREAD

**Issue by alganet** [YahooArchive/mojito#273]
RFC2616 says:

```
The individual values of the numeric status codes defined for
HTTP/1.1, and an example set of corresponding Reason-Phrase's, are
presented below. The reason phrases listed here are only
recommendations -- they MAY be replaced by local equivalents without
affecting the protocol.
```

It should be possible to return something like this:

```
return ac.done({}, {http: {code: 400, status: "Malformed recipient"}, serialize: 'json'});
```

Similar functionality could be available on `ac.error()` as well.

I'm willing to send a pull request if needed. What do you think?

**Comment by mojit0** [comment]
I can't speak to how we'd prioritize merging this feature, but if you have a use case requirement and would like to contribute a solution we'll definitely consider it.

**Comment by rwaldura** [comment]
I'd like to understand better, it feels a little strange to me: why issue a raw HTTP message from the framework?

**Comment by rwaldura** [comment]
@mojit0 Could this be done from the middleware? Should it be?

**Comment by mojit0** [comment]
@rwaldura It will depend on the nature of the error/status code in question. Certain codes might be detectable as early as middleware in the pipeline, but most are far more likely to occur within the engine and well after the middleware has handed off to the Mojito core and the server-side controller logic.

**Comment by alganet** [comment]
@rwaldura Our team is developing an application that also behaves like an API when needed. There is a mojitProxy-less mojit that responds to raw RESTful requests that must follow a strict contract.

One of our major requirements is to have a really small payload and fast network performance, and reusing the status message seems like a good approach, even compatible with AJAX clients via `xhr.statusText`.

Our current implementation uses the default "Warning" HTTP header for this, but it isn't as canonical as customizing the status message, since the "Warning" header has been used for expressing errors in the entity body, not related to the request itself. 

Tunneling the errors through the entity body itself and sending a generic HTTP status is one of our possible choices, but this generates overhead in both clients and proxies trying to calculate the Content-Length of the response.

**Comment by FabianFrank** [comment]
@alganet I think this absolutely makes sense, when providing APIs.

I have one more use case and I think it answers the why question of @rwaldura :
It is a huge help to not only see a generic error code but a specific description of the real error from the perspective of an API customer. A lot of good Yahoo APIs even give you a URL in the description where you can read more. I think Mojito should support this feature, because it can make APIs implemented in Mojito a lot better.

**Comment by rwaldura** [comment]
Understood. It does sound cool, but our primary use-case is presentation -- building Web Services, not so much. 
Which isn't to say this is a bad idea, or that folks shouldn't do it, but I think we need to stay focused. This feels a bit out of scope for us at this point. 
A pull request would go a long way! ;)

**Comment by FabianFrank** [comment]
@rwaldura Makes sense. I agree with the primary use case, but often APIs are somewhat a by-product of a cool app and we shouldn't force them to be worse than necessary, so I gave you a pull request. :-)

**Comment by mridgway** [comment]
Added in PR #300.
