### ISSUE TITLE
Affinity bug in i13n.common.js

### ISSUE THREAD

**Issue by ricallinson** [YahooArchive/mojito#278]
This file has "common" affinity yet depends on a "server" affinity addon. As such it fails "dependsOn" checks done in the "action-context" once deployed to a client.

The problem can be found at line 220:

I13nAddon.dependsOn = ['config', 'http', 'url'];

**Comment by rwaldura** [comment]
What is the fix? What needs to be removed from the dependsOn array?

**Comment by ricallinson** [comment]
Option 1:

There could be two versions of the Addon, one for the server and one for the client.

Option 2:

Remove "http" from the "dependOn" array and add it as a YUI require. However, this would always throw a warning as the http Addon will never be found by the client.

```
I13nAddon.dependsOn = ['config', 'url'];

Y.mojito.addons.ac.i13n = I13nAddon;

}, '0.1.0', {requires: [
    'mojito',
    'mojito-addon-http'
]});
```

I can submit a patch for Option 2 if required?

In either case the i13n Addon should not be part of the public facing Mojito library as it cannot be used by anyone other than Yahoo!

**Comment by ricallinson** [comment]
Pull request submitted https://github.com/yahoo/mojito/pull/287
