### ISSUE TITLE
Add YAF ModelList to Mojito

### ISSUE THREAD

**Issue by trungpham** [YahooArchive/mojito#288]
Introduce YUI ModelList to Mojito.

If the model list has already been populated from the server side by calling the load() function, then we need to serialize the list and pass it over to the browser. This way the browser will not need to reload the model list again.

Also, add a class method to reference the model list.

/**
@param {String} id where id is an identifier pointing to the modelList instance.
@returns {ModelList}
/*
ModelList.get = function(id){

}

Note. This is not the same as the instance method get(id) where it returns an instance of the Model.

**Comment by caridy** [comment]
This is going to be addressed in 0.6 thru `express-state`. I will keep this around for reference. In the current mojito, only stuff set thru `ac.pageData.set()` and `ac.data.set()` will be serialized and rehydrated in the client side.

**Comment by caridy** [comment]
this is done.
