### ISSUE TITLE
[bz5707658] ac.http.redirect does not work from a child mojit

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#293]
`ac.http.redirect` is not working because i'm using it in the child mojit. 
The parent calls `ac.composite.done` to collect the children views and stop the execution. 
But here, `ac.http.redirect` stops the child mojit's execution & the parent  still keeps on running.

`mojito/app/addons/ac/http.server.js`  - the "redirect" method calls `ac.done` inside, which will not work in parent-chilren mojit scenario.

**Comment by caridy** [comment]
@rwaldura this is still an issue, feel free to create a card in trello for prioritization.

**Comment by rwaldura** [comment]
Workaround is to pass the parent's action context to the child mojit.

**Comment by caridy** [comment]
Mixing "ac" from parent to child chould be problematic. I think the solution for this is also related to the work I have done on error propagation from child to parents, etc. I will think more about this.

**Comment by sqawasmi** [comment]
seems this related to an issue i have, ac.http.redirect is not working in HTMLFrameMojit child, this was working fine in 0.5.2 but got broken by 0.5.3

**Comment by caridy** [comment]
@sqawasmi can you provide an repro case?

**Comment by sqawasmi** [comment]
the following is a sample repo:
https://github.com/sqawasmi/htmlframe_mojit_mojito_issue_293.git

in mojito 0.5.2, requesting the following link:
http://127.0.0.1:8666/
will redirect you to http://127.0.0.1:8666/index

however, running the same application using mojito 0.5.3 will give HTTP/1.1 200 OK with "null" in the body.

**Comment by caridy** [comment]
That's all I need, thanks @sqawasmi. I will try to get this fix for `0.5.5` on monday.

**Comment by caridy** [comment]
This fix will be included in tomorrow's release!
