### ISSUE TITLE
Use Y.namespace() when declaring components

### ISSUE THREAD

**Issue by mridgway** [YahooArchive/mojito#319]
It seems odd that instead of using Y.namespace() when declaring components, we expect the namespaces to already be created by mojito.common.js. The mojito.common.js seems unnecessary (the version is in there, but it's out of date) if we simply call Y.namespace in individual components.

Example: `Y.mojito.addons.ac.config = Addon;` vs. `Y.namespace('mojito.addons.ac').config = Addon;`

**Comment by isao** [comment]
agreed, we should clean these up.

**Comment by mojit0** [comment]
+1

**Comment by drewfish** [comment]
+1

Mojito.common.js should go away in my mind. (The only place Y.mojito.version is used is in HTMLFrameMojit controller.  Given that the version number is significantly out of date, I don't think anyone would mind if we just dropped it altogether.)

**Comment by mridgway** [comment]
If we want to remove it completely we would have to phase it out due to a BC break. The 'mojito' mojit has to exist due to all components (including mojits) requiring it. Also some of the management tools define a mojito app as a component that contains a server.js or index.js that require 'mojito': https://github.com/yahoo/mojito/blob/develop/source/lib/management/utils.js#L432
