### ISSUE TITLE
[bz4970604] Lazyload: got "mojitYuiModules is undefined" from dispatch.common.js

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#33]
Got "mojitYuiModules is undefined" from dispatch.common.js

logger.log('Dispatching an instance of "'+(instance.id || '@'+instance.type)+'/'+command.action+'" with the modules: ['+mojitYuiModules.join(', ')+']', 'info', NAME);

To reproduce:

cd qetest/source/applications/frameworkapp/common
mojito start
http://localhost:4081/#LazyParent

**Comment by caridy** [comment]
Solved in 0.5.x while dispatch does not know about yui modules anymore.
