### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#344]
http://developer.yahoo.com/cocktails/mojito/docs/faq/#moj-lazyloading
nce by first dispatching the **LazyLoadMoit** as a proxy to the client.

http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_framework_mojits.html#lazyloadmojit
azyLoadMojit is really a proxy mojit that dispatches **it’s** binder and

**Comment by rwaldura** [comment]
@zhouyaoji ping ping

**Comment by zhouyaoji** [comment]
Sorry, I didn't see this sooner. Can you please label docs bugs as "documentation" in the future? Thanks, that's how I generally find issues that I should be working on.

**Comment by rwaldura** [comment]
you bet. sorry about that, will do so in the future

**Comment by zhouyaoji** [comment]
No problem. I've fixed the problems.
