### ISSUE TITLE
[bz4998187] calling ac.params.getFromUrl() twice in code causes mojit test app to fail

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#36]
I have a library of functions that check URL parameters and so I called ActionContext.params.getFromUrl() twice:

1) in libary
2) in mojit controller.server.js

The code ran fine but when I ran "mojit test app ." on my app, this caused the tests to fail with the error:

```
Method getFromUrl() wasn't called the expected number of times.
```

**Comment by caridy** [comment]
old issue. closing.
