### ISSUE TITLE
shared assets have wrong URL, especially when staticHandling.appName is "/"

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#375]
Consider an app with shared assets and staticHandling.appName = "/".  In that case, the shared assets should have URL prefix "/static/" or perhaps "/static/shared/" (it's debatable).  However, it looks like they have prefix "/static///".

**Comment by redonkulus** [comment]
@rwaldura this would be a blocker from upgrading to 0.4.

Even with changing appName to something other than "/", I still do not get the shared assets to load.

**Comment by rwaldura** [comment]
is this related to #358?

**Comment by drewfish** [comment]
@rwaldura That's unknown, since the root cause of #358 is unknown.
