### ISSUE TITLE
bad text formatting

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#384]
at http://developer.yahoo.com/cocktails/mojito/docs/getting_started/mojito_getting_started_tutorial.html#make-the-application
under "modify the sample mojit"
the code box includes text at the bottom:

```
      });
    }
  };
}, '0.0.1', {requires: ['mojito', 'HelloMojitModelFoo']});

As you can see the "controllers" are just an array of JavaScript objects, and the "action" is just a method called on the controller object.
The result of the method are communicated back to Mojito through the ``actio
 ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by zhouyaoji** [comment]
Thanks for spotting that issue. The formatting was also affecting the ordered list. I've fixed the problem.
