### ISSUE TITLE
Mojito 0.3.30 fails on tutorial app

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#387]
Originally a follow-up to issue #223 by @ramses0.

$ mojito version
path.existsSync is now called fs.existsSync.
Version of mojito is 0.3.30

...following: http://developer.yahoo.com/cocktails/mojito/docs/getting_started/mojito_getting_started_tutorial.html#make-the-application

$ mojito test app .path.existsSync is now called fs.existsSync.
[warn] undefined: overriding application config value: env
[WARN] MojitoServer: your mojit "HelloMojit" has a server affinity and these client-related deps: node-base, node-core, dom-core, dom-base, node-event, node-pluginhost, node-screen, dom-screen, dom-style, dom-style, node-style
[WARN] MojitoServer: Mojito may be unable to start, unless you have provided server-side DOM/host-object suppport

...snip...

timers.js:103
if (!process.listeners('uncaughtException').length) throw e;
^
TypeError: Cannot read property 'documentElement' of null
at Object.YUI.add.requires [as fn](/usr/local/lib/node_modules/mojito/node_modules/yui/dom-base/dom-base-min.js:7:50)

...tutorial or mojito is broken.

Yep, this is "base case" stupidly following the tutorial. I tried changing controller.server.js to controller.client.js to maybe adjust the "affinity" (?) but it gave different error messages which I am not familiar enough with mojito / node to figure out off the top of my head.

Quickstart worked: http://developer.yahoo.com/cocktails/mojito/docs/quickstart/ but the "HelloWorld" has not. Literally just mojito create app ; mojito create mojit ; mojito start as suggested by the tutorial.

This is with latest npm / node and the 0.3.30 mojito freshly downloaded. npm install mojito -g ... and copy/paste all the config stuff from the tutorial examples. Server starts after tweaking, but gives a different error message which I don't have on this computer. Shouldn't be hard to reproduce.

@gissues:{"order":33.33333333333332,"status":"backlog"}

**Comment by jenny** [comment]
I've added this to the sprint for investigation.

**Comment by FabianFrank** [comment]
@jenny I was approached by several people in Bangalore about this. The breaking/crashing unit tests are fixed with: https://github.com/yahoo/mojito/pull/395

**Comment by bitlyfied** [comment]
still no fix? I just started playing with Mojito, and breaking a HelloWorld app makes it look pretty bad...

**Comment by caridy** [comment]
@bitlyfied it was fixed in 0.4.2 few days ago, but it is not tagged as stable yet!

**Comment by add0n** [comment]
Fixed in 0.4.2. Closing.
