### ISSUE TITLE
Missing Mustache template crashes Mojito process

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#39]
I tried moving the generated index.mu.html to another directory to see what would happen. In the logs I get:

[MOJITO](1322856027466) mojito-mu: Rendering template "undefined"

/home/y/share/node/mojito/app/addons/view-engines/mu.server.js:33
                    if (err) { throw err; }
                               ^
Error: EISDIR, Is a directory

And the process crashes.

**Comment by rwaldura** [comment]
Fairly sure we've resolved this.
