### ISSUE TITLE
mojito test broken in 0.4.1

### ISSUE THREAD

**Issue by FabianFrank** [YahooArchive/mojito#393]
hi guys,

it seems that mojito test is broken in 0.4.1. I can't run it in an example app.

$ npm install mojito@0.4.1 -g
$ mojito create app hello
$ cd hello
$ mojito create mojit bar
$ mojito test app .
✖ Invalid command: undefined
usage:
mojito <command> [<params>] [<options>]
$ mojito help
Available commands: build, compile, create, docs, gv, help, info, jslint, start, test, version

It works fine in 0.4.0.

regards,
fabian

**Comment by mridgway** [comment]
Fixed in 0.4.2.
