### ISSUE TITLE
Documentation (or blog post) about bundling and packaging Mojito for App Stores

### ISSUE THREAD

**Issue by jshirley** [YahooArchive/mojito#403]
I know that Axis is available in the iOS App Store, which is fantastic.

One of the things preventing me from jumping into Mojito development is the lack of documentation and information on how to properly bundle a Mojito app under the App Store.

Should we use Phonegap? Something else? How does mojito-shaker come into play?

Having some official guidance on this would be extremely useful.

Thanks!

**Comment by caridy** [comment]
@jshirley yes, this is definitely an area we need to put some effort to help early adopters, but it is very early for that in my opinion. Although, I can answer some of the questions:
- yes, u can use `mojito build html5app --context "device:iphone" to generate the HTML/JS/CSS for the infamous www folder, and use it in phonegap, or even to generate stuff that will work within Sensha for example.
- yes, u can use shaker once u decide to build that html5app, I don't remember the exact command for that. cc @dferreiroval for more details on this. I think u have to run mojito-shake --context "device:iphone", then mojito build ....
- in axis, we use regular WebViews, with our own sugar layer to support YUI.CL for communication between mojito app and the native layer, but this is about to change with a formal container that we are about to release which is similar to phonegap but targeting mojito apps as first class citizens.

**Comment by rwaldura** [comment]
Hi Jay:

Thanks for your interest in Mojito. I have to agree with you, at this point in time there's a marked lack of documentation on how to do this. We've been working on this though! We are preparing an announcement, and you can expect a clear direction (and code!) in a few weeks. 

If your project just cannot wait, PhoneGap is a possible option for the time being. 

Shaker only deals the comboing of assets. It's used to optimize loading performance; doesn't solve the AppStore problem.

**Comment by rwaldura** [comment]
See also [forum thread](http://developer.yahoo.com/forum/Yahoo-Mojito/Tools-for-creating-an-xcode-wrapper-/1344092139642-b496922f-885f-4dfb-8fc3-140f38d344e8).

**Comment by caridy** [comment]
@rwaldura I still think Shaker plays a role on the code that you put into your device. It will definitely clean up the code/comment/log statements. It can help with the cssembed rutine (very useful for iOS in my opinion to avoid flicking). It can help with the rollups (avoid having 100 files to load/parse/cache by the webview, instead u load only few created by shaker. etc.

**Comment by jshirley** [comment]
Thanks very much guys, this is great to hear. I'm really excited about seeing what's coming down the pipe.

Thanks for the additional insight into shaker, @caridy -- that was basically how my understanding was. I built a sort of stop gap before seeing shaker for my YAF application. It works to at least reduce the requests down.

**Comment by diervo** [comment]
Let me know if you have any doubt in Shaker! I will love to help.
By the way we are re-writting it for the new Mojito, so keep tunned! :)

Anything let me know! Thanks guys!

2012/8/17 Jay Shirley notifications@github.com

> Thanks very much guys, this is great to hear. I'm really excited about
> seeing what's coming down the pipe.
> 
> Thanks for the additional insight into shaker, @caridyhttps://github.com/caridy-- that was basically how my understanding was. I built a sort of stop gap
> before seeing shaker for my YAF application. It works to at least reduce
> the requests down.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yahoo/mojito/issues/403#issuecomment-7831829.

## 

Diego Ferreiro Val
@diervo
