### ISSUE TITLE
application.json >> builds -> html5app doc

### ISSUE THREAD

**Issue by caridy** [YahooArchive/mojito#409]
In the documentation, the object to configure the build is called "build":

http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_configuring.html#build-obj

but according to lib/management/commands/build.js, it should be "builds". Here is the snipped:

```
    // Is there a "builds" section for this "type" in the appConfig
    if (appConfig.builds && appConfig.builds[type]) {
        config = appConfig.builds[type];
    }
```

**Comment by zhouyaoji** [comment]
Thanks, Caridy. I've updated the docs, correcting the issue.

**Comment by rwaldura** [comment]
@zhouyaoji doc bug

**Comment by zhouyaoji** [comment]
Thanks, Ren. I already fixed the problem. See the following page: http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_configuring.html#build-obj

**Comment by rwaldura** [comment]
silly me!
