### ISSUE TITLE
store.getMojitTypeDetails() computes too many dependencies

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#413]
The results of `getMojitTypeDetails()` and `expandInstanceForEnv()` of the resource store return controller and binder YUI module requirements.  For controllers, the list is too large, since it includes everything in the mojit (including all shared resources), regardless of whether the controller `{requires:[]}` them or not.

Found by @dferreiroval.

**Comment by caridy** [comment]
Closing this after the work on 0.5.x. /cc @drewfish
