### ISSUE TITLE
html5app build - assets path

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#415]
Upon doing a `build html5app`, the code that is generated (say, index.html) refers to the assets using absolute path, for example **`/static/mojito/autoload/perf.client.js`**

However, the files are created within `artifacts/builds/html5app/static/` folder, sub-folder `static` relative to `index.html`.

As such, I feel that the references generated must be relative - **`./static/mojito/autoload/perf.client.js`**

**Comment by drewfish** [comment]
You can fix this using the `builds.html5app.forceRelativePaths` in application.json.

http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_configuring.html#html5app-obj

**Comment by gvaish** [comment]
@drewfish Great. I missed this option :)

**Comment by rwaldura** [comment]
see also related tickets #375, #284, #358.
