### ISSUE TITLE
support css compilers, such as sass or less

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#417]
Mojito should provide a way to support CSS compilers, such as sass or less.

**Comment by drewfish** [comment]
I have a start of this here:
https://github.com/drewfish/mojito/commits/rs-contents

It needs more unit tests.

Also, I think mimetype calculations need to be done a bit differently.  They should probably move to an RS addon, so that they can be done at server-start time (and so that other addons, such as one that stitches in sass or less, can tweak them).

**Comment by caridy** [comment]
@drewfish can you share the sass addon somehow so I can adjust my less and coffee ones based on the one u just finish?

**Comment by drewfish** [comment]
You can find it here:
http://somefancy.com/drew/mojito/pkg-sass.tgz

**Comment by caridy** [comment]
This will be supported thru locator plugins in 0.6

**Comment by realistschuckle** [comment]
Is this issue closed? I see that mojito has gone past version 0.6.

**Comment by caridy** [comment]
@realistschuckle I will call this closed. We never officially released those compilers though.

**Comment by realistschuckle** [comment]
How about un-officially? :) Do they live in a branch at which I could look and maintain their usage on my own?
