### ISSUE TITLE
[bz5264469] middleware tests are not run during 'mojito test app'

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#42]
There should be a standard for middleware unit tests so that mojito can pull them and run them with the app tests.

**Comment by caridy** [comment]
@isao is this still an issue?

**Comment by isao** [comment]
I think so..

**Comment by isao** [comment]
yes still a bug I think. I don't see any related test.js code changes. closing here and tracking at yahoo/mojito-cli-test#3
