### ISSUE TITLE
[bz5264893] when using a group setting which is not defined in dimension.json, the error msg is misleading

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#43]
when using group setting is not defined in dimension.json, for example, in application.json, changed the "environment:testing" to "environment:testing1", the error msg is as following:

✖ The settings group '{"environment":"testing1"}' has already been added.
    Error: The settings group '{"environment":"testing1"}' has already been
added.
    at Object._processRawBundle
(/usr/local/lib/node_modules/mojito/lib/libs/ycb.js:196:27)
    at Object.read (/usr/local/lib/node_modules/mojito/lib/libs/ycb.js:35:26)
    at Object._readConfigYCB
(/usr/local/lib/node_modules/mojito/lib/store.server.js:1959:26)
    at Object._readAppConfigNC
(/usr/local/lib/node_modules/mojito/lib/store.server.js:1197:30)
    at Object.preload
(/usr/local/lib/node_modules/mojito/lib/store.server.js:252:38)
    at Object.addMojitoToExpressApp
(/usr/local/lib/node_modules/mojito/lib/index.js:134:15)
    at Object.createServer
(/usr/local/lib/node_modules/mojito/lib/index.js:263:14)
    at Object.start
(/usr/local/lib/node_modules/mojito/lib/management/utils.js:410:56)
    at Object.run
(/usr/local/lib/node_modules/mojito/lib/management/commands/start.js:78:9)
    at main (/usr/local/lib/node_modules/mojito/lib/management/cli.js:112:13)

✖ Mojito was not started!

**Comment by caridy** [comment]
@drewfish is this still an issue or the msg was corrected?

**Comment by drewfish** [comment]
I'm pretty sure this was fixed in commit 8d4ce645 (though that function was later renamed to `validateContext()`).
