### ISSUE TITLE
Full support for REST

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#430]
This issue is a superset of issue #429, which we'll keep focused on supporting PUT requests only.

Quoting @mojit0:

_A proper REST implementation should support GET, POST, PUT, and DELETE. For performance reasons it's sometimes useful to also support HEAD requests. As part of that support HTTP status codes other than 200 can indicate success and should be properly handled._

**Comment by caridy** [comment]
#429 was resolved. Can we close this? /cc @rwaldura

**Comment by rwaldura** [comment]
closing -- we'll track this as a feature request when it comes up
