### ISSUE TITLE
Passing the ipaddress / port to listen to

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#436]
Wondering if there's a dynamic way to specify the port to listen to and the ipaddress to bind to?

I need a configuration that's compatible with OpenShift installation. See https://github.com/openshift/nodejs-example/blob/master/server.js for example.

Also since I need mojito to be started using node, my updated server.js looks like below:

``` javascript
process.chdir(__dirname);

var mojito = module.exports = require('mojito').createServer();

var ipaddr = process.env.OPENSHIFT_INTERNAL_IP || "127.0.0.1";
var appPort = process.env.OPENSHIFT_INTERNAL_PORT || 8080;

mojito.listen(appPort, function(err) {
    if (err) {
        utils.error('There was an error starting the application:\n');
        utils.error(err);
        console.log('\n');
        utils.error('Mojito was not started!\n', null, true);
        return;
    }
    console.log('Mojito started\n');

});
```

**Comment by mojit0** [comment]
There is a pull request for dynamic port but not for ip address. We can put that in our queue.

**Comment by gvaish** [comment]
@mojit0 I think it would be a good feature to have... specially if you have a machine with multiple IPs configured.

**Comment by mojit0** [comment]
0.4.7 and 0.5.0pr2 support a new update which removes the start() call and replaces it with listen() support. The index.js and server.js files of existing applications need to be updated to support these releases but they should solve this issue.
