### ISSUE TITLE
html5app build - URIs are escaped

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#446]
Noticed that the `build html5app` command escapes the URIs. It that intentional?

For example, if my "/" has the following in the HTML generated

`<link href="/static/TodoMojit/assets/base.css" rel="stylesheet" type="text/css" />`

I get the following output in `index.html`

`<link href="static&#x2F;TodoMojit&#x2F;assets&#x2F;base.css" rel="stylesheet" type="text/css" />`

Notice that `/` has been escaped to `&#x2F`

**Comment by drewfish** [comment]
What version of Mojito?

**Comment by gvaish** [comment]
0.4.42

**Comment by isao** [comment]
that's an odd version, but this is fixed on develop and will be included in next release 0.4.9

**Comment by gvaish** [comment]
My fault... it should have been 0.4.2
