### ISSUE TITLE
TodoMVC app in Mojito

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#449]
@clarle @capecodehq @addyosmani @gvaish 
Multiple concurrent efforts to write such an app. Great initative folks! 
Could we join forces and merge into one app?

**Comment by rwaldura** [comment]
This is already tracked at https://github.com/addyosmani/todomvc/issues/131
Please ignore.

**Comment by gvaish** [comment]
@rwaldura Well, I guess we may have excitingly different approaches to solve the same problem - contrasting case studies! :)
