### ISSUE TITLE
Unify --context flag

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#45]
"mojito start" has a --context flag that accepts arguments like
"lang:es,environment:dev".

"mojito build" has a --context flag that accepts arguments like
"lang=es&device=iphone".

These contexts both filter into the system in different ways. "start" passes the arguments directly in code, while "build" uses the argument to generate a URL.

These flags should take the same argument, or perhaps use different names since they filter into the system in different ways. "build"'s context is really more of a set of parameters for the URL today.

**Comment by mridgway** [comment]
Fixed by #336.
