### ISSUE TITLE
ycb - removed but referenced

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#457]
In 0.4.43 release, seems like `ycb` addon has been removed but still referenced to in `addons/rs/selector.server.js` (Line 22)

https://github.com/yahoo/mojito/blob/develop/lib/app/addons/rs/selector.server.js#L22

Need quick fix.

**Comment by mridgway** [comment]
ycb is now a separate node_module. You will have to run `npm install` in your application in order to pull down the new dependency.

**Comment by gvaish** [comment]
Hmmm... noticed that `ycb` was pulled in already in `node_modules/mojito/node_modules/ycb` folder. But then why this error?

Using `node @ 0.6.20`, `npm @ 1.1.37` and `mojito @ 0.4.43`.

**Comment by mridgway** [comment]
What is the error that you are getting?

**Comment by gvaish** [comment]
Seemed liked a version conflict in global mojito install vs local mojito install.
Global was 0.4.2 while local was 0.4.43.

`./node_modules/mojito/bin/mojito start` works
