### ISSUE TITLE
Example "using_configs" and "global_assets" gives error on Firebug

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#46]
I am executing the example in the developer-guide - using_configs
When running on Firefox, I see the below error on Firebug:

Y.mojito is undefined
[Break On This Error] window.YMojito = { client: new Y.mojito.Client({

**Comment by zhouyaoji** [comment]
I don't see any errors in Firebug when I run either the  'using_configs' or the 'global_assets' app. I was running Firefox 13.0.1 on a Mac OS X, Version 10.6.8. Can you please specify the OS and version of Firefox that you are running? Thanks.

**Comment by zhouyaoji** [comment]
Because this example has been updated and Mojito has had many changes in the past three months, this issue might have been resolved, so I'm closing it for now.
