### ISSUE TITLE
[bz5815270] build html5app command - the "builds.html5app" key in "application.json" is not context aware.

### ISSUE THREAD

**Issue by ricallinson** [YahooArchive/mojito#461]
When running the "mojito build html5app" command, the "builds.html5app" key in "application.json" is not changed when a context is provided.

**Comment by rwaldura** [comment]
@jenny mentioned in SoS

**Comment by ricallinson** [comment]
Pull request here https://github.com/yahoo/mojito/pull/466

**Comment by rwaldura** [comment]
See #466.

**Comment by rwaldura** [comment]
please update bz ticket 5815270 when you close this, thanks!

**Comment by isao** [comment]
done, thank you @rwaldura

**Comment by rwaldura** [comment]
this issue was resolved by applying PR #490
