### ISSUE TITLE
"expand instance" tunnel call doesn't pass along the action

### ISSUE THREAD

**Issue by drewfish** [YahooArchive/mojito#465]
The tunnel call to expand the instance (appears as `GET /static/{mojit}/definition.json`) doesn't pass along the action on the controller that is in flight. Mojito itself doesn't need that, but shaker2 uses it.

**Comment by diervo** [comment]
Thanks for track the new shaker need/feature! :)

**Comment by caridy** [comment]
This is not longer valid, shaker do not use the action anymore :), closing.
