### ISSUE TITLE
Combo-ing the Binders

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#487]
The HTMLFrameMojit adds on "script" tag each for the mojit used in a page. On a complex page, the number can go in 10s - which is a huge number of requests.

**Feature Request**

The binders may be served via a combo URL - configurable

**Comment by redonkulus** [comment]
You can use Shaker for handling assets from CDN and rolling up files:
https://github.com/yahoo/mojito-shaker

**Comment by gvaish** [comment]
Will give a shot and report the updates.

**Comment by caridy** [comment]
You should strike for not serving any static asset from your node.js server, instead versioning them and serving them from CDN. As @redonkulus you should use shaker.

**Comment by gvaish** [comment]
@caridy That's precisely the idea... CDN serving after combo-ing the binders.

Will checkout the shaker... had done earlier but received some gotchas. That was in 0.x, now it's 2.x. Tempted to give a full shot this time!

**Comment by caridy** [comment]
This is now solved with the new infrastructure in 0.5.x. Closing.
