### ISSUE TITLE
Serve static files via CDN

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#488]
The autoload, binder, model, assets etc files are served from the hosting server location (`/static/myapp/autoload/something.client.js` or `/static/mymojit/binders/index.js` or even `/static/mymojit/assets/js/something.css`).

**Feature Request**

Allow (using config) serving via CDN.

**Comment by redonkulus** [comment]
You can use Shaker for handling assets from CDN and rolling up files:
https://github.com/yahoo/mojito-shaker

**Comment by gvaish** [comment]
@redonkulus Understand the rollup part... but the CDN?

I remember to have tried out Shaker but noticed that it required server-affinity controller. Having only either common and/or client didn't work out.

Will give a shot again.

But the question still remains... once I get the compiled JS files, how do I configure to use them via CDN?

**Comment by redonkulus** [comment]
@gvaish there is a section in the Shaker docs that menions deployment via Yahoo CDN or Amazon:

http://developer.yahoo.com/cocktails/shaker/shaker_usage.html#environment-configuration

Basically just creating the following configuration in your `application.json` file:

```
{
    "settings": ["environment:prod"],
    "shaker": {
        "task": "s3",
        "config": {
            "client": {
                "key": "<key>",
                "secret": "<secret>",
                "bucket": "<bucket>"
            }
        }
    }
}
```

@dferreiroval can confirm.

**Comment by diervo** [comment]
Seth is right, but if youre installing Shaker 2.x the api changed. Still on process of documenting... Let me know...

**Comment by gvaish** [comment]
Hmmm... but how about a non-S3, non-Y CDN... at least for non yui-files?

Is it already there (and a simple conf) or WIP or I overlooked?

**Comment by redonkulus** [comment]
@gvaish on the same doc page, its mentioned that you can create your own deployment task using Buildy to deploy to another CDN:

http://developer.yahoo.com/cocktails/shaker/shaker_usage.html#deploying-elsewhere

Hope that helps.

**Comment by drewfish** [comment]
Closing as "wontfix", since this is taken care of by shaker.

For further discussion of shaker's features, it be best to hold those discussions on shaker's github issues.
