### ISSUE TITLE
Compatibility with Node.js 0.8

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#496]
`package.json` at the root says:

```
"engines": {
        "node": ">= 0.4.0 < 0.7.0",
        "npm": ">= 1.0.0"
    },
```

Yet v0.4.3 claims to be compatible with Node 0.8:
https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_3
via PR #381.

**Comment by isao** [comment]
issue closed a while back with yahoo/mojito/pull/498
