### ISSUE TITLE
Mojito seems to override Y.log, without maintaining the original contract

### ISSUE THREAD

**Issue by sdesai** [YahooArchive/mojito#512]
On the client, Y.log seems to get displaced in mojito-client.client.js, and the new version doesn't seem to fire the log event fired by Y.log (when CE is present). As a result code listening for the log event is never notified.

Would it be better for Mojito to listen to the event itself to add custom behavior, instead of displacing the original implementation? If not, can we re-introduce the original behavior in the displaced version.

**Comment by caridy** [comment]
Related to issue #70, we definitely need to clean this up. I wonder what is this logger doing that YUI logger doesn't. The only thing that I can see from the source is the new 'MOJITO' level. Now that node.js env is a first class citizen for YUI, YUI logger should support all the stuff we need, even when we don't have `Y` on a file, we should be able to require `require('yui/yui-base')` to get `Y.log` there.

**Comment by caridy** [comment]
FYI, fixed in 0.5.0pr2, and will be documented as part of 0.5.0. Y.log is the logger in mojito, no more wrapping.
