### ISSUE TITLE
[Doc] Broken link to the RS source

### ISSUE THREAD

**Issue by imalberto** [YahooArchive/mojito#515]
http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_resource_store.html

In the section "how does the rs work", there is a broken link that presumably points to the source.

https://github.com/yahoo/mojito/blob/develop/source/lib/store.server.js

Result: 404

**Comment by zhouyaoji** [comment]
Thanks for catching that. I've corrected the link.
