### ISSUE TITLE
coverage fails to instrument the following code

### ISSUE THREAD

**Issue by dmorilha** [YahooArchive/mojito#520]
original code:
                    videos.push({$
                        abstract: abs,$
                        thumbnail: thumbnail,$
                        title: title,$
                        url: url$
                    });$

instrumented code:
                    _yuitest_coverline("/tmp/mojitotmp/controller.server.js", 64); videos.push({$
                        abstract: abs,$
                        _yuitest_coverline("/tmp/mojitotmp/controller.server.js", 66); thumbnail: thumbnail,$
                        title: _yuitest_coverline("/tmp/mojitotmp/controller.server.js", 67); title,$ 
                        url: _yuitest_coverline("/tmp/mojitotmp/controller.server.js", 68); url$
                    });$

**Comment by caridy** [comment]
@dmorilha this is probably an issue for: https://github.com/yui/yuitest

**Comment by caridy** [comment]
Can we close this @dmorilha?
