### ISSUE TITLE
Running 'mojito test mojito path-to-mojit/mojit' returns an error.

### ISSUE THREAD

**Issue by zhouyaoji** [YahooArchive/mojito#526]
I created a new app w/ a mojit using Mojito v0.4.4 and then tried to use the test command to test the mojit: $ mojito test mojit path-to-mojit/mojit'  Mojito threw an error similar to that specified in the closed issue 387: https://github.com/yahoo/mojito/issues/387

Also see the following related issue: https://github.com/yahoo/mojito/issues/525

The commands and the error message returned by Mojito are listed below:

$ mojito create app test_app
$ cd test_app
$ mojito create mojit test_mojit
$ mojito test mojit mojits/test_mojit

warn: (yui): NOT loaded: mojito-client
warn: (yui): NOT loaded: mojito-perf
warn: (yui): NOT loaded: mojito-perf

/opt/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:1147
            throw (e || new Error(msg));
                        ^
TypeError: Cannot read property 'documentElement' of null
    at Object.fn (/opt/local/lib/node_modules/mojito/node_modules/yui/dom-base/dom-base-min.js:7:50)
    at [object Object]._attach (/opt/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:701:33)

**Comment by isao** [comment]
works now.

```
% mojito create app issue526
path.existsSync is now called `fs.existsSync`.
creating app type named 'issue526'
(using "default" archetype)
✔ app: issue526 created!
✔ mojito done.

% cd issue526/
%  mojito create mojit test_mojit
path.existsSync is now called `fs.existsSync`.
creating mojit type named 'test_mojit'
(using "default" archetype)
✔ mojit: test_mojit created!
✔ mojito done.

% mojito test mojit mojits/test_mojit
path.existsSync is now called `fs.existsSync`.
warn: (yui): NOT loaded: mojito-perf
warn: (yui): NOT loaded: mojito-perf

Test Results:
artifacts/test/result.xml


✔  passed test_mojit-tests :: test_mojit user tests :: test mojit
✔  passed test_mojitModelFoo-tests :: test_mojitModelFoo user tests :: test mojit model

Total tests: 2  ✔ Passed: 2   ⚑ Deferred: 0 ✖ Failed: 0   100% pass rate

% mojito version
path.existsSync is now called `fs.existsSync`.

Version of mojito is 0.4.8

✔ mojito done.
```
