### ISSUE TITLE
Add /CONTRIBUTING.md

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#529]
See https://github.com/blog/1184-contributing-guidelines/
and e.g. https://github.com/yui/yeti/blob/master/CONTRIBUTING.md
YUI is preparing one as well.

I propose we merely copy 
https://github.com/yahoo/mojito/wiki/Contributing-Code-to-Mojito
into /CONTRIBUTING.md.

**Comment by rwaldura** [comment]
YUI's is here: 
https://github.com/yui/yui3/wiki/Contributing.md

I notice ours doesn't link to our coding standard: https://github.com/yahoo/mojito/wiki/Coding-Standards
It probably should.

**Comment by caridy** [comment]
@rwaldura can we close this?

**Comment by rwaldura** [comment]
Not quite yet.
@zhouyaoji can you create a file CONTRIBUTING.md that merely points to 
https://github.com/yahoo/mojito/wiki/Contributing-Code-to-Mojito
Thanks!

**Comment by zhouyaoji** [comment]
Sure, done!
