### ISSUE TITLE
[bz4788123] All autoload modules are attached twice

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#53]
As it turns out, the autoload modules aren't being -loaded- twice, but -attached- twice. By "attach" I mean that the fn part of "Y.add(name, fn, ...)" is being called. So, for binders[1], the fn is called once as it is added to the page-level YUI instance (the one in which mojito-client runs), and again for the YUI instance that is made for the mojit invocation. (Using sharedYUIInstance just means that all mojit invocations share a single YUI instance -- they don't use the page-level YUI instance, though perhaps they should.)

[1] and their dependencies, which is probably where this autoload comes from

**Comment by caridy** [comment]
Solved by the new loader infrastructure in 0.5.x
