### ISSUE TITLE
views multiple devices example is missing selector configs in application.json

### ISSUE THREAD

**Issue by tufandevrim** [YahooArchive/mojito#549]
The example at
http://developer.yahoo.com/cocktails/mojito/docs/code_exs/views_multiple_devices.html
is missing following config values in application.json:

{ "settings": [ "device:android" ], "selector": "android" },
  { "settings": [ "device:blackberry" ], "selector": "blackberry" },
  { "settings": [ "device:iphone" ], "selector": "iphone" }

**Comment by zhouyaoji** [comment]
Thanks for filing this issue. I've corrected the code snippets in the "Setting Up this Example" section and added documentation for using context configs and the 'selector' property in the "Implementation Notes" section. In addition, the example "Dynamically Adding CSS to Different Devices" was also missing the context "device:iphone" and the 'selector' property in both the implementation notes and steps: both have been corrected.
