### ISSUE TITLE
[bz5301600] mojito-client should require YUI intl

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#56]
In this scenario:
- An app running in prod mode (useRollups: true)
- A binder that will do nothing with the templates or lang.

Under those circustances, an error will be reported:

Uncaught TypeError: Object #<Object> has no method 'add'

**Comment by caridy** [comment]
This is invalid, each lang bundle should require it's dependencies, including "intl" if it needs to call Y.Inlt.add.
