### ISSUE TITLE
documentation - bad links in docs under docs/topics

### ISSUE THREAD

**Issue by dmitris** [YahooArchive/mojito#561]
the links in the file docs/topics/action-context.md (https://github.com/yahoo/mojito/blob/develop/docs/topics/action-context.md) are all bad - point to URLs like  http://developer.yahoo.com/cocktails/mojito/api/Assets.common.html
but should be now:
http://developer.yahoo.com/cocktails/mojito/api/classes/Assets.common.html

Is this file and the rest of docs/topics still needed and used?  A bit confusing that we have docs/dev_guide/topics and docs/topics - if docs/topics is deprecated, I would suggest to remove it.

There are bad links in other files under docs/topics, for example:
https://github.com/yahoo/mojito/blob/develop/docs/topics/guides/binders.md
"The MojitProxy API is here." , and "broadcast"

https://github.com/yahoo/mojito/blob/develop/docs/topics/guides/controllers.md links to "ActionContext" as "/action-context" which of course gives 404 when viewed on GitHub.

**Comment by zhouyaoji** [comment]
Hi Dmitri, I'm discussing with team members what to do about 'docs/topics' now. Hope to have a solution soon.

**Comment by zhouyaoji** [comment]
Hi Dmitri,

I've moved 'docs/topics/getting-started-guide' to 'docs/getting-started-guide' and removed 'docs/topics'. The 'docs/topics' were used to create more formal documentation, which meant the information was for the most part redundant, so it was better to remove the directory to avoid the confusion that you mentioned. I'll start working on the bugs for the getting-started-guide next. Thanks again.
