### ISSUE TITLE
documentation - missing controller.server.js code from Step 9 in http://developer.yahoo.com/cocktails/mojito/docs/code_exs/calling_yql.html

### ISSUE THREAD

**Issue by dmitris** [YahooArchive/mojito#562]
http://developer.yahoo.com/cocktails/mojito/docs/code_exs/calling_yql.html
(Calling YQL from a Mojit) in the "Setting Up this Example" section, Step 9 misses the code for the controller.server.js - 

```
9. Modify the mojit controller to get data from the model by replacing the code in controller.server.js with the following:

10. Create the file assets/index.css for the application’s CSS with the following:
```

The corresponding source code is in https://github.com/yahoo/mojito/blame/master/docs/dev_guide/code_exs/calling_yql.rst line 310:

```
#. Modify the mojit controller to get data from the model by replacing the code in ``controller.server.js`` with the following:

#. Create the file ``assets/index.css`` for the application's CSS with the following:
```

The example file:
examples/developer-guide/model_yql/mojits/flickr/controller.server.js
is OK, so we just need to brush it up for it to be jslint error-free and copy the code into a code-block in the missing area.

**Comment by zhouyaoji** [comment]
Thanks, Dmitri. I've added the missing code for the controller. Thanks for reviewing the docs!
