### ISSUE TITLE
mojito/lib/app/autoload/mojito.common.js has a stale hardwired version 0.2

### ISSUE THREAD

**Issue by dmitris** [YahooArchive/mojito#571]
The code in https://github.com/yahoo/mojito/blob/develop/lib/app/autoload/mojito.common.js is:

``` javascript
YUI.add('mojito', function(Y, NAME) {

    Y.namespace('mojito').version = '0.2';
    Y.namespace('mojito.trans');
```

should be replaced with a dynamic setting from package.json, otherwise running an application shows in the browser an incorrect title "Powered by Mojito 0.2".

**Comment by caridy** [comment]
This was fixed in 0.5.2 by @lzhan
