### ISSUE TITLE
Routes regex use not documented

### ISSUE THREAD

**Issue by redonkulus** [YahooArchive/mojito#598]
I noticed there is no mention of using Regex to configure a route in the mojito configuration page. 

Here is the page I would expect it to be in:
http://developer.yahoo.com/cocktails/mojito/docs/intro/mojito_configuring.html#routing

It mentions call, params, path and verbs but not regex.  A user in the freenode forum had a use case for this problem but couldn't find a solution since it was undocumented.

**Comment by rwaldura** [comment]
let's

**Comment by zhouyaoji** [comment]
I've updated the source docs, so you can view using regular expressions for routing at the following URLs:
- https://github.com/yahoo/mojito/blob/develop/docs/dev_guide/intro/mojito_configuring.rst#routing
- https://github.com/yahoo/mojito/blob/develop/docs/dev_guide/intro/mojito_configuring.rst#using-regular-expressions-to-match-routing-paths

YDN seems to be making template changes, so I was unable to publish the latest docs on YDN. I'll get in contact with them and push them as soon as possible.

**Comment by redonkulus** [comment]
This looks good. Thanks.

**Comment by zhouyaoji** [comment]
Great, I just published the doc to YDN.
