### ISSUE TITLE
Doc Correction

### ISSUE THREAD

**Issue by ajchen-yahoo** [YahooArchive/mojito#602]
On "http://developer.yahoo.com/cocktails/mojito/docs/faq/#moj-params-controller-binder", the process described for passing information from the controller to the binder is incorrect. You need to use ac.instance.config instead of this.config.

**Comment by zhouyaoji** [comment]
Thanks for filing the issue. I've updated the docs: http://developer.yahoo.com/cocktails/mojito/docs/faq/#moj-params-controller-binder

Can you verify that the information is accurate and clear?

**Comment by ajchen-yahoo** [comment]
Looks good to me. Thanks!

**Comment by zhouyaoji** [comment]
Great, thanks for reviewing the updated doc!
