### ISSUE TITLE
update documentation for version 0.4.6's backward compatibility issue

### ISSUE THREAD

**Issue by shiweiwei97** [YahooArchive/mojito#618]
Upgrading to mojito@0.4.6 will require the following code changes in server.js.

``` javascript
var Mojito = require('mojito');
var app = Mojito.createServer();
// Mojito 0.4 and 0.5 compatibility...
module.exports = app.start ? app.start() : app;
```

**Comment by caridy** [comment]
@imalberto can you update the release notes?

**Comment by rwaldura** [comment]
release notes found at https://github.com/yahoo/mojito/wiki/ReleaseNotes0_5_0pr1

**Comment by caridy** [comment]
@rwaldura those notes are for 0.5.0pr1, while the same issue is on 0.4.6

**Comment by imalberto** [comment]
Already updated release notes.

https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_6
