### ISSUE TITLE
Easier way to pass information to child mojit template

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#62]
It's so easy to pass information from a child mojito to a parent, with ac.meta.store/retrieve.

The other way around, not so much. We came up with three approaches:

1)
http://devel.corp.yahoo.com/cocktails/mojito/docs/topics/mojito_composite_mojits.html#dynamically-creating-child-mojits
;

2) Hiding on a parent template tag and reading on the child binder;

3) Inject on ac.composite.command before ac.composite.done:

ac.composite.command.params.body.some_thing = 'some value';

And retrieving on the child controller as:

ac.params.body('some_thing');

---

But they do not look as straightforward as possible. We believe it could be easier if we could use the ac.meta.store/retrieve, or passing it as a meta to the parent .done() controller call is also good. As in:

ac.composite.done({}, {'child_mojit_name': {'some_thing': 'some_value'}});

**Comment by caridy** [comment]
`ac.pageData.set('foo', 'some value here')` does this, just remember to require `mojito-data-addon`. This data is also available in all templates rendered under the same request/page thru `{{page}}` object.
