### ISSUE TITLE
Expand instances are bleeding

### ISSUE THREAD

**Issue by redonkulus** [YahooArchive/mojito#651]
I'm using latest from develop-perf branch and am noticing that the same spec object is being returned for routes that map to different specs. Sort of confusing but I think its related to recent caching enhancements to Mojito.

Mojit  'page' controller will look for the children object, if found, it sends that the ac.composite, otherwise it will generate one dynamically.

In either case, the spec from the first route is always returned in my app. 

Gist of the files: https://gist.github.com/3920557

**Comment by caridy** [comment]
@imalberto can u close this?

**Comment by imalberto** [comment]
Fix reviewed and submitted in develop-perf. See PR #663
