### ISSUE TITLE
correct the test descriptor filename in tests/README

### ISSUE THREAD

**Issue by dmitris** [YahooArchive/mojito#662]
https://github.com/yahoo/mojito/blob/develop/tests/README#L169 says:

arrow --driver=selenium --reuseSession=true
     ./unit/lib/app/addons/ac/test_descriptor.json

but the indicated directory does not have test_description.json file - only ac_test_description.json:

```
$ ls unit/lib/app/addons/ac
ac_test_descriptor.json     test-device.server.js
test-analytics.common.js    test-http.server.js
test-assets.common.js       test-intl.common.js
test-carrier.server.js      test-meta.common.js
test-composite.common.js    test-output-adapter.common.js
test-config.common.js       test-params.common.js
test-cookie.client.js       test-partial.common.js
test-cookie.server.js       test-url.common.js
test-deploy.server.js
```

Fix: change test_description.json to ac_test_description.json

Also, if  we recommend to run with --reuseSession=true, we probably should suggest running
arrow_selenium --open=firefox
first, otherwise, the arrow command fails if it cannot find any opened Selenium sessions.

**Comment by caridy** [comment]
@lzhan can we close this? Was this fixed?

**Comment by isao** [comment]
That entire readme is woefully out of date

we should replace it with something simple like: "to run mojito's unit tests: `cd path/to/mojito && npm test`".. etc.

**Comment by isao** [comment]
..now that @lzhan hooked up the npm scripts (mojito@>=0.6.1). and/or link to @zhouyaoji arrow docs

**Comment by zhouyaoji** [comment]
Removed the information on executing tests and linked to the twiki on how to run tests instead.
