### ISSUE TITLE
Specifying binder doesn't work

### ISSUE THREAD

**Issue by denchen** [YahooArchive/mojito#665]
When I try to specify which binder file to use, Mojito doesn't seem to want to use that file, always insisting on using the file with the same name as the template

ac.done( { <stuff here> }, { view: { name: "blah", binder: "foo" } } );

This should use blah.hb.html and foo.js, but at least on my environment (Mojito 0.4.5), it insists on using blah.js.

My console output is:
mojito-client: Mojito Client state: paused. yui-base-min.js:12
mojito-client: Created binder "BlahBinderIndex3" for DOM node "yui_3_5_1_2_10_1351121699154_6" yui-base-min.js:12
In blah.js yui-base-min.js:12
mojito-client: Mojito Client state: active. yui-base-min.js:12

(I have foo.js, which creates BlahBinderIndex2, and blah.js, which creates BlahBinderIndex3)

**Comment by caridy** [comment]
This should not be an issue in 0.5.x (latest). Closing this. Feel free to re-open if you have any issue with it.
