### ISSUE TITLE
upgrading to 0.4.8 breaks 0.4.4 app

### ISSUE THREAD

**Issue by ooskapenaar** [YahooArchive/mojito#669]
Hi, 

after upgrading from to 0.4.8 of Mojito I get following error (at end)

line 162 has the classical Mojito example code:
        Y.mojito.controllers[NAME] = {

The Y Object passed into the anonymous function that has been added to YUI does not have a "mojito" property at all. Hence the error below.  Any suggestions?

/usr/local/bin/node --debug-brk=53556 /usr/local/bin/mojito start
debugger listening on port 53556
path.existsSync is now called `fs.existsSync`.
[WARN](1351239102644) mojito-perf: microtime not found. Recorded times will not have microsecond accuracy
[DEBUG](1351239105520) Mojito HTTP Server initialized in 4680ms.

{ '0': '✔',
  '1': ' ',
  '2': '\t',
  '3': 'M',
  '4': 'o',
  '5': 'j',
  '6': 'i',
  '7': 't',
  '8': 'o',
  '9': ' ',
  '10': 's',
  '11': 't',
  '12': 'a',
  '13': 'r',
  '14': 't',
  '15': 'e',
  '16': 'd',
  '17': ' ',
  '18': '\'',
  '19': 'y',
  '20': 'C',
  '21': 'o',
  '22': 'c',
  '23': 'k',
  '24': 'p',
  '25': 'i',
  '26': 't',
  '27': '\'',
  '28': ' ',
  '29': 'o',
  '30': 'n',
  '31': ' ',
  '32': 'h',
  '33': 't',
  '34': 't',
  '35': 'p',
  '36': ':',
  '37': '/',
  '38': '/',
  '39': 'l',
  '40': 'o',
  '41': 'c',
  '42': 'a',
  '43': 'l',
  '44': 'h',
  '45': 'o',
  '46': 's',
  '47': 't',
  '48': ':',
  '49': '3',
  '50': '0',
  '51': '0',
  '52': '0',
  '53': '/',
  '54': '\n' }
[DEBUG](1351239107479) static-handler: serving static path: /
[MOJITO](1351239107484) server: request received
[MOJITO](1351239107484) qeperf: request received
[MOJITO](1351239107484) server: START
[MOJITO](1351239107484) mojito-resource-store-adapter: resource store adapter init
[DEBUG](1351239107484) mojito-dispatcher: Dispatcher created
[MOJITO](1351239107484) qeperf: dispatching command for DC.index
[MOJITO](1351239107484) qeperf: expanding partial mojit instance
[MOJITO](1351239107486) qeperf: mojit instance expansion complete: yui_3_5_1_2_4_1351239099931_75
[MOJITO](1351239107486) qeperf: loading YUI modules for YUI instantiation: yui_3_5_1_2_4_1351239099931_75
[MOJITO](1351239107486) mojito-loader: loading /Users/rrrw/Projects/Node/Mojito/yCockpit/mojits/DC/controller.server.js, /Users/rrrw/Projects/Node/Mojito/yCockpit/mojits/DC/models/dc.server.js
[MOJITO](1351239107584) mojito-loader: SUCCESS
[MOJITO](1351239107590) qeperf: YUI instance created: yui_3_5_1_2_4_1351239099931_75
[MOJITO](1351239107590) mojito-dispatcher: Cached a YUI instance with key: 'DC?runtime=server&lang=en-US&langs=en-US,en'
[INFO](1351239107591) mojito-dispatcher: Dispatching an instance of 'DC/index' with the modules: [dbmodulemongo, modulecsv, DC, dcCloudModel, mojito-perf, mojito, mojito-config-addon, yui-base, json-stringify, oop, event-custom-base, mojito-view-renderer, array-extras, mojito-util, mojito-output-adapter-addon, querystring-parse, querystring-stringify, querystring-stringify-simple, mojito-route-maker, mojito-url-addon, mojito-assets-addon, mojito-http-addon, mojito-cookie-addon, mojito-params-addon, mojito-composite-addon, mojito-action-context, mojito-controller-context, mojito-resource-store-adapter, intl-base, event-custom-complex, intl, mojito-dispatcher, mojito-hb, mojito-mu]
[MOJITO](1351239107591) qeperf: dispatching instance of 'yui_3_5_1_2_4_1351239099931_75/index'
[MOJITO](1351239107591) qeperf: YUI use: yui_3_5_1_2_4_1351239099931_75

/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:1147
            throw (e || new Error(msg));
                        ^
TypeError: Cannot read property 'controllers' of undefined
    at Object.YUI.add.requires [as fn](/Users/rrrw/Projects/Node/Mojito/yCockpit/mojits/DC/controller.server.js:162:17)
    at proto._attach (/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:701:33)
    at proto._use (/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:1055:21)
    at proto.use (/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:816:15)
    at runMojit (/usr/local/lib/node_modules/mojito/lib/app/autoload/dispatch.common.js:219:45)
    at modulesLoaded (/usr/local/lib/node_modules/mojito/lib/app/autoload/dispatch.common.js:270:21)
    at YUI.add.msg (/usr/local/lib/node_modules/mojito/lib/app/autoload/dispatch.common.js:298:25)
    at YUI.add.Loader.load.Y.Get.script.onSuccess (/usr/local/lib/node_modules/mojito/lib/app/autoload/loader.common.js:63:21)
    at YUI.add.pass (/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:3791:26)
    at YUI.add.Y.Get.js.check (/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:3814:21)

Process finished with exit code 1

**Comment by rwaldura** [comment]
@ooskapenaar have you checked the release notes since 0.4.4?

https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_5
https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_6
https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_7
https://github.com/yahoo/mojito/wiki/ReleaseNotes0_4_8

**Comment by ooskapenaar** [comment]
Hi, 
thanks for the hint. I still had the old server.js. With the new server.js I get roughly the same error 

...
[MOJITO](1351760862926) qeperf: YUI use: yui_3_5_1_2_4_1351760856053_73
            throw (e || new Error(msg));
                        ^
TypeError: Cannot read property 'controllers' of undefined
    at Object.YUI.add.requires [as fn](/Users/rrrw/Projects/Node/Mojito/drg_cockpit/mojits/DC/controller.server.js:41:17)
    at proto._attach (/usr/local/lib/node_modules/mojito/node_modules/yui/yui-nodejs/yui-nodejs.js:701:33)
...

As stated originally, line 41 is

```
    Y.mojito.controllers[NAME] = {
```

 (BTW. There was no index.js in   `mojito/lib/app/archetypes/app/default`  although suggested in the 0_4_7 release notes.)

**Comment by mojit0** [comment]
One other change between versions that might be affecting you depending on the files in question is that modules are no longer automatically added by mojito. So errors of the type Y.mojito being undefined mean you need a requires array entry for 'mojito'. Errors around slots on the action context like ac.params mean you need a requires array entry for 'mojito-params-addon', and so on. Is it possible that one of these kind of issues is happening?

**Comment by ooskapenaar** [comment]
thanks for the answer.  yes definitely possible.  I am going through the code now and adding these explicit dependencies.    Are there comments in the moijto code somewhere that explain more about this change?

**Comment by ooskapenaar** [comment]
I just grepped out the possibilities - these all have to potentially be explicitly included, right? e.g. I often use the composite addon

'mojito-analytics-addon'
'mojito-assets-addon'
'mojito-carrier-addon'
'mojito-composite-addon'
'mojito-config-addon'
'mojito-cookie-addon'
'mojito-cookie-addon'
'mojito-deploy-addon'
'mojito-device-addon'
'mojito-http-addon'
'mojito-intl-addon'
'mojito-meta-addon'
'mojito-output-adapter-addon'
'mojito-params-addon'
'mojito-partial-addon'
'mojito-url-addon'
'mojito-hb'
'mojito-hb'
'mojito-mu'
'mojito-mu'
'mojito-action-context'
'mojito-controller-context'
'mojito-dispatcher'
'mojito-loader'
'mojito-logger'
'mojito-mojit-proxy'
'mojito-client'
'mojito-test'
'mojito-output-handler'
'mojito-perf'
'mojito-perf'
'mojito-resource-store-adapter'
'mojito-rest-lib'
'mojito-route-maker'
'mojito-client-store'
'mojito-tunnel-client'
'mojito-util'
'mojito-view-renderer'
'mojito-resource-store'

**Comment by ooskapenaar** [comment]
Last comment:  FIXED!

**Comment by rwaldura** [comment]
Team: would it be possible to write a conversion tool for 0.5 that would detect such errors? W/o necessarily fixing them, would just issue a warning.

**Comment by caridy** [comment]
Yeah, it sounds like we finally have a strong reason to implement `mojito upgrade` command.

**Comment by ooskapenaar** [comment]
2c: this issue arose because I assumed that the patch version 0.0.x change means I don't have to read the release notes because the upgrade won't break my app.  perhaps review your version numbering protocol.   

also it seems that the change that I ultimately had to address is described in the release notes for 0.5.0... a feature "leak"?

otherwise the changes reqd to make things run were actually minimal. thanks for your help.
