### ISSUE TITLE
[bz4649669] Dispatches with expand instance errors and no adapter error fn hang the request open

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#67]

**Comment by rwaldura** [comment]
??? what does this mean?

**Comment by drewfish** [comment]
Probably that when `dispatch()` (which is what runs a mojit) calls `store.expandInstanceForEnv()` (which is what calculates all the resources needed to run the mojit) and there is an error, that `dispatch()` doesn't return the error appropriately (or doesn't catch the exception), eventually leading to neither `ac.done()` nor `ac.error()` being called.

**Comment by drewfish** [comment]
See https://github.com/yahoo/mojito/blob/develop/lib/app/autoload/dispatch.common.js#L118

**Comment by drewfish** [comment]
Reopened, since it is still a valid problem.

**Comment by rwaldura** [comment]
Thanks.

**Comment by caridy** [comment]
Fixed as part of 0.5.x, we now use the proper adapter.error when something happen within the dispatch workflow.
