### ISSUE TITLE
Error when running 'mojito info'

### ISSUE THREAD

**Issue by zhouyaoji** [YahooArchive/mojito#715]
$ mojito version

Version of mojito is 0.4.8

$ mojito help

path.existsSync is now called `fs.existsSync`.
Available commands: compile, create, docs, gv, help, info, jslint, start, test, version

$ mojito info

path.existsSync is now called `fs.existsSync`.
✖ Error getting ino.
# It appears Mojito removes the 'f' from the command 'info', so it can't find the correct command.

**Comment by isao** [comment]
I fixed the typo in my commit 2528ac3d7381916578ce985f228a1feb91b92424 but for some reason it still awaits code review on pull #700

I'll also note the the command is only prints the name, description, and version from a package.json file in the current directory. Were you in an app dir?

**Comment by isao** [comment]
fixed typo. error message otherwise as before, but could be improved (is working, just unclear to user that the command works only in an npm dir)
