### ISSUE TITLE
ondemand breaks mojitProxy.render

### ISSUE THREAD

**Issue by denchen** [YahooArchive/mojito#717]
Using Mojito 0.4.5, if the "yui" section of application.json contains:

"dependencyCalculations": "ondemand"
    or
"dependencyCalculations": "precomputed+ondemand"

then calling mojitProxy.render() from a binder returns an error similar to the following:

Uncaught TypeError: undefined is not a function    view-renderer.common.js:26
Renderer    view-renderer.common.js:26
privateRender    mojito-client.client.js:96
MojitoClient.doRender    mojito-client.client.js:749
(anonymous function)    mojito-client.client.js:453
MojitProxy.render    mojit-proxy.client.js:123
(anonymous function)    blah.js:60
b.Subscriber._notify    combo:79
b.Subscriber.notify    combo:80
b.CustomEvent._notify    combo:79
b.CustomEvent._procSubs    combo:79
b.CustomEvent.fireSimple    combo:79
b.CustomEvent.fire    combo:79
C.fn    combo:138

If "dependencyCalculations" is simply "precomputed" or undefined, the error goes away. I didn't see anything in the documentation that suggests that mojitProxy.render() wouldn't work in such circumstances, or things would need to be configured differently for it to work.

**Comment by caridy** [comment]
Closing this in favor of 0.5.x where we use a completely different approach to load and render ondemand mojits. this should not be an issue there.
