### ISSUE TITLE
REST Lib: Params passed through Y.mojito.lib.REST.PUT() can't be retrieved by ac.params.getFromUrl() in underlying WS

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#72]
wsWithPUTParams: function(hostport, sprintNum, cb){
            var url = "http://" + hostport + "/restWS/printPUTParams";
            var params = {
                project: "Mojito",
                sprint: sprintNum
            };
            var config = {
                timeout: 5000,
                headers: {}
            };

```
        Y.mojito.lib.REST.PUT(url, params, config, function(err, response)
```

{
                if (err) {
                    return cb(err);
                }
                cb(null, response.getBody());
            });
        }

In the underlying WS (/restWS/printPUTParams), I am accessing the params using ac.params.getFromUrl():

printPUTParams: function(actionContext){
            var project = actionContext.params.getFromUrl("project");
            var sprint = actionContext.params.getFromUrl("sprint");

```
        var output = "<p id=\"output\">This is sprint " + sprint + " for
```

the project " + project + "</p>";
            actionContext.done(output);
        }

But I cannot access the parameters using getFromUrl(). As per the docs, params for PUT are the keys & values to add as query parameters.

**Comment by isao** [comment]
Y.mojito.lib.REST will probably be deprecated soon
