### ISSUE TITLE
Content Error

### ISSUE THREAD

**Issue by ghost** [YahooArchive/mojito#736]
In the "Getting Started" section there is a defect with the last phrase.  The tick before "Creating" is a link and should not be. You are also missing the rest of the content for the section.

**Comment by zhouyaoji** [comment]
HI oshiwoshy,

Are you referring to the Getting Started section in the YDN docs (http://developer.yahoo.com/cocktails/mojito/docs/getting_started/) or the getting-started-guide directory in
the Mojito GitHub repo (https://github.com/yahoo/mojito/tree/develop/docs/getting-started-guide)? I didn't see the error in the YDN docs, but maybe I'm missing something. Thanks.

**Comment by ghost** [comment]
Hi,

I was referring to the following link:
http://developer.yahoo.com/cocktails/mojito/docs/.

Getting Startedhttp://developer.yahoo.com/cocktails/mojito/docs/#getting-started

Ready to start creating apps? You’ll start with a quickstart that will show
you how to install Mojito and then get up an running with your first Mojito
app. Once you have Mojito installed and are familiar with the basic steps
of creating an app, you can walk through the
`http://developer.yahoo.com/cocktails/mojito/docs/#id1
Creating

Right before "Creating" is a tick that I don't believe you mean to be there.

-Joshua Price

**Comment by zhouyaoji** [comment]
Thanks, Joshua. I've corrected the issue in the source file for the documentation. YDN has just revamped their site, so I'm unable to update the docs right now. I've contacted the YDN team and hope to resolve the error as soon as possible. Thanks for catching that and filing this GH issue.

**Comment by ghost** [comment]
No problem. Glad I could help!

**Comment by zhouyaoji** [comment]
The documentation has been corrected and published to YDN. Thanks again.
