### ISSUE TITLE
css-assets are not generated well when they contain non ascii characters

### ISSUE THREAD

**Issue by ItsAsbreuk** [YahooArchive/mojito#783]
This issue is seen in 0.5.0pr4, in previous 0.4.8 it went well.

Suppose the next css file:

.price:before {
        content: "Price: €";
        padding-right: 4px;
}

When generated http://localhost:8666/static/MyMojit/assets/index.css, then the last } is missing. When I have n-times a non-ascii character, then the n-last characters are missing. It seems to me something like the length of the file to be responded is calculated by the number of characters, where as a true utf-8 takes more space.

Marco.

**Comment by caridy** [comment]
@ItsAsbreuk this was fixed in develop-perf already, and the fix will be part of 0.5.0GA

**Comment by ItsAsbreuk** [comment]
All right then. Sorry for mentioning. Just trying to help.

Marco.

**Comment by drewfish** [comment]
Hi @ItsAsbreuk,

Thanks for filing this issue -- I think you did the right thing. It just happens that we had already seen (and fixed) this already.  It's always better to over-report a problem than have it lost/forgotten, so your report was good.  Keep sending the issues, and we'll address them as best we can!

Drew

**Comment by ItsAsbreuk** [comment]
Hi Drew, all right, I'll do so. Thx for your response.

Marco.
