### ISSUE TITLE
Allow passing of app config to model objects

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#8]
Allow app-level config to be available in models, so that things like API
hostnames, etc.. can be stored in the config.

Example:      

``` javascript
Y.mojito.models.foo_model = {

        init: function(cfg, app) {
            if(cfg){
                this.cfg = cfg;
            }
            if(app){
                this.app = app;
            }
        },
```

**Comment by drewfish** [comment]
Instead of just passing static configs to init(), I'd like instead to pass a "model context" (or "model proxy").  The configs (app or mojit) can be gotten from this proxy.  This would be a larger change though -- a bit of an architectural change.

**Comment by isao** [comment]
This pull request was accepted and applied. It's in 0.3.8 now. Thank you!

**Comment by jithine** [comment]
Just wanted to ask if there is any documentation for this? I am trying to access config in defaults.json in model.

**Comment by drewfish** [comment]
I didn't find any documentation addressing this specifically. I do notice that if a model as an `init()` method it is passed a single parameter which contains the instance config.  (The instance config is a merge of the spec (as found in application.json) and the defaults.json.)

(Not sure why this issue got closed as an accepted pull request... :confused: )

**Comment by jithine** [comment]
I tried passing ac.config to init() But for some reason it's coming as null. Though there is no config in the spec for my mojit, I was expecting it to contain the ones from defaults.json. - which brings another question, is defaults.json mojit level or app level ? If it's mojit level what is the standard way to define app level configurations and how to use it?

**Comment by drewfish** [comment]
The `init()` method is called automatically by the mojito as the model is created.

One approach is to pass the config you want to each method of your model as needed, something like `model.foo(config, ...)`.  You can get the config similar to what you were doing with ac.config.  However, ac.config is an API object (and it only exists if your controller depends on the `mojito-config-addon`).  You'll need to pass the results of `ac.config.get()` or `ac.config.getAppConfig()`.

**Comment by jithine** [comment]
Ok. this is what I had to do to get this work. call model.init(ac.config) and define setting in "config" of the mojit in application.json.
Which is all fine but how do I have a config defined once for the entire application? I thought putting a defaults.json in app level will take care of it, but it didn't.

**Comment by drewfish** [comment]
Here's the API documentation for the ac.config addon:
http://developer.yahoo.com/cocktails/mojito/api/classes/Config.common.html

**Comment by drewfish** [comment]
Generally if you want to define a config for the whole application you want to put it into `application.json`.  Then you can use `ac.config.getAppConfig()` to get those values out.

**Comment by jithine** [comment]
Thank you very much. Got it working.
