### ISSUE TITLE
[bz4647674] Remove dependency on express and revert back to connect only

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#80]
There is nothing in express that we are using that connect doesn't provide.

**Comment by rwaldura** [comment]
see related issue #126

**Comment by rwaldura** [comment]
See also bz5753621 for an example of how Express is currently used -- i.e. we need to support the upload use-case even though we drop Express.

**Comment by drewfish** [comment]
Closing, since the latest thinking is to build mojito _more_ on express.
