### ISSUE TITLE
[bz4647676] Remove prototypal singletons

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#81]
In general, scour the codebase for prototypal objects that only have one instance of them ever created and replace with an object literal.

**Comment by rwaldura** [comment]
why? is it a performance optimization?

**Comment by isao** [comment]
somewhat, but I think the main point was it added unnecessary complexity. No need to `new Foo()` and call an instance method, when all that is ever needed is to just call the method...

**Comment by rwaldura** [comment]
sounds like housekeeping issue: I'd rather address this on an ongoing basis -- during commit review -- than with a ticket
