### ISSUE TITLE
[bz4647788] Don't make unnecessary calls to the shell for file system commands

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#84]
The yuidoc script is bad about this.

**Comment by mridgway** [comment]
Are there other places that we need to clean up other than yuidoc? If not, this can be closed since #243 is merged.

**Comment by drewfish** [comment]
We spawn a java process to generate instrumented code for code coverage, in app/commands/test.js.

**Comment by mridgway** [comment]
Ok that makes sense. Once Arrow supports code coverage and is open sourced we will be able drop the java code.

**Comment by rwaldura** [comment]
we'll use Istanbul for code coverage
