### ISSUE TITLE
[bz4647783] jslint cli option to lint a single file

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#85]

**Comment by dmorilha** [comment]
would be nice to have it reporting to stdout instead of creating files :P

**Comment by dmitris** [comment]
Do the --print and -p options (https://github.com/yahoo/mojito/pull/199 and https://github.com/yahoo/mojito/pull/251) solve the issue? If so, let's close it, otherwise, let's specify what exactly needs to be done.

**Comment by caridy** [comment]
@isao can we close this?

**Comment by isao** [comment]
I'd like to keep it open -- will tackle this once the cli gets moved to it's own package

**Comment by caridy** [comment]
/ping @isao, can you move this to `mojito-cli-lint`?

**Comment by isao** [comment]
@caridy yes I'll include this issue or completed feature in mojito-cli-jslint after I create org repo for it

**Comment by isao** [comment]
yes, I'd generally like to act on individual files for jslint as well as the other commands where possible. I'm closing this but tracking for the general case here: yahoo/mojito-cli/issues/21 thanks!
