### ISSUE TITLE
[bz4647743] Remove static handler's check for malicious paths

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#87]
we should be able to just remove statements like this, because Mojito closes all bad URLs down:

// Potentially malicious path
if (~path.indexOf('..')) {
return forbidden(res);
}
@gissues:{"order":66.66666666666666,"status":"backlog"}

**Comment by caridy** [comment]
0.5.x static handler relies entirely on the store and the urls produced by the store, anything else is ignored (404).
