### ISSUE TITLE
Mojito Quickstart page needs to update node.js requirement

### ISSUE THREAD

**Issue by AndyOfLinux** [YahooArchive/mojito#871]
Currently the Mojito Quickstart page shows requirement of "node.js < .8".  This is incorrect.  Mojito works OK (per github closed issues) with  "v0.8.1" version of node.js.  Docs need to be updated.

**Comment by rwaldura** [comment]
@zhouyaoji 
http://developer.yahoo.com/cocktails/mojito/docs/quickstart/

Thanks @AndyOfLinux for the report. Welcome to Mojito!

Note that you can issue pull requests against the documentation, e.g.
https://github.com/yahoo/mojito/blob/develop/docs/dev_guide/quickstart/index.rst

**Comment by zhouyaoji** [comment]
Thanks, I've updated the range of versions of Node.js that Mojito can run on.
