### ISSUE TITLE
problem encoding comboSep param character within yui -> config -> group -> app

### ISSUE THREAD

**Issue by diervo** [YahooArchive/mojito#879]
I have this configuration for overriding the combo url with Shaker:
"yui": {
            "config": {
                "groups": {
                    "app":{
                        "base": "http://a.l.yimg.com/",
                        "comboBase": "http://a.l.yimg.com/zz/combo?",
                        "comboSep": "&",
                        "combine": true,
                        "root": ""
                    }
                },
              "comboSep": "&"
            }
        }

On the deploy addon (line162) you guys filter the outside one, but no the one within groups.app:

 yuiConfigEscaped = Y.mojito.util.cleanse(yuiConfig);
            if (yuiConfig.comboSep) {
                yuiConfigEscaped.comboSep = yuiConfig.comboSep;
            }

The result on the source code shipped:
... 
"comboSep":"\u0026","combine":true,"root":""}},"comboSep":"&", ...

**Comment by drewfish** [comment]
We are guarding against not "cleansing" yui.config.conboSep, but we're not guarding against cleansing yui.config.groups.app.comboSep.

**Comment by jenny** [comment]
Tracked here: https://trello.com/card/search-gh879-shaker-groups-app-combosep-should-support-just-like-yui-config-combosep/504e5e3b7cd1578456fc430f/307

**Comment by caridy** [comment]
In develop already, should be available as part of 0.5.2 release.
