### ISSUE TITLE
[bz4558998] Ability to programmatically set headers for static files

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#9]
We should probably open up a function within the static handler middleware so users can provide massaging of responses for static files.

[Massaging of] Expires, Last-Modified, or any custom headers someone might want.

**Comment by drewfish** [comment]
There is already some config variables for this (see "cache" and "maxAge" in "staticHandling" in application.json).  Not sure how well it works though :(

There's also an idea (filed separately) to give user-provided middleware access to the ResourceStore, which would be enough for them to write their own customized static handler.

**Comment by caridy** [comment]
I don't think this is valid anymore since prod quality apps will probably get assets from CDN, in which case the headers are controlled by the CDN itself (and mojito-shaker). If mojito serves those assets, the current configurations that we have should be good enough. Closing.
