### ISSUE TITLE
CSS needs to be mojit's CSS

### ISSUE THREAD

**Issue by nonopolarity** [YahooArchive/mojito#912]
In http://developer.yahoo.com/cocktails/mojito/docs/code_exs/calling_yql.html

It is said that

```
Replace the contents of assets/index.css for the application’s CSS with the following
```

but since in the application.json, it is specified to use the mojit's CSS:

```
"css": [
            "/static/flickr/assets/index.css"
```

So either application.json should change to use the application's CSS file, or the description should say add the CSS code to the mojit's CSS file.

**Comment by zhouyaoji** [comment]
Thanks, fixed!
