### ISSUE TITLE
Remove query string routing

### ISSUE THREAD

**Issue by add0n** [YahooArchive/mojito#94]
Make sure there are no docs or examples about it.

**Comment by epuidokas** [comment]
Does this invalidate https://github.com/yahoo/mojito/issues/7 ?

**Comment by zhouyaoji** [comment]
No, Mojito allows you to specify routing parameters using an object as showin in issue #7. The use of specifying routing paramaters with a query string has been deprecated. Instances of using a query string to specify routing parameters have been removed from the docs and code examples except for two deprecation notices. I'll close issue #7 as well. Thanks.
