### ISSUE TITLE
ac.composite.done() to specify the view to follow the behavior of ac.done()

### ISSUE THREAD

**Issue by kinlum** [YahooArchive/mojito#948]
If we do a 

```
ac.done(data, {"view": {"name": "detail"}});
```

but then, if now this Mojit has a child or children, then we need to use `ac.composite` like this:

```
ac.composite.done({ "template" : data });
```

So it works, but we can't specify the  `"view": {"name": "detail"}`  part easily.  If `ac.done` and `ac.composite.done` work mostly the same except one has no children and one does, would it be ok if `ac.composite.done` can have the feature to work like the following:

```
ac.composite.done({ "template" : data, "view": {"name": "detail"} });
```

or 

```
ac.composite.done({ "template" : data, "view": {"name": "index"} });
```

---

As a side note, I wonder why we don't just have `ac.done()` and it will check automatically whether it has children or not, so that if it does, then it will process just like `ac.composite.done()` does.  Is it really for speed concerns?  Otherwise in some GUI frameworks, if a view has a subview, it is automatically drawn, and we won't need to pay special attention as to whether a view has children or not.

**Comment by caridy** [comment]
I can take this for 0.5.3, it seems a low-impact change. About the ac.done vs ac.composite.done, that have to be discussed. But basically, adding complexity into the mix is a recipe for failure. They are not the same thing, while composite is way more complex.

**Comment by caridy** [comment]
Closing this now that PR #950 was merged. It will be ready in 0.5.3, in the meantime, you can try it using "develop" branch. The details on of syntax is in the PR. Basically ac.done and ac.composite.done are equivalent in terms of API.
