### ISSUE TITLE
Need some documentation on Resource Store internal data structures

### ISSUE THREAD

**Issue by jlecomte** [YahooArchive/mojito#968]
It would be EXTREMELY useful to have some documentation on the format of the various internal data structures manipulated by the Resource Store and how those data structures are modified during preload, etc.

**Comment by isao** [comment]
check out the docs at http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_resource_store.html and the tests https://github.com/yahoo/mojito/blob/develop/tests/unit/lib/app/autoload/test-store.server.js etc

as you know, the team is in the process of changing structures and apis though

**Comment by isao** [comment]
@jlecomte after checking the docs, you can try some forensics with your app and this patch https://github.com/isao/mojito/commit/8fbac40f7 (or just `npm i mojito@git://github.com/isao/mojito.git#issue968` in your app dir)

in your app, do `mojito start` and you'll get a dump of some files in /tmp containing the app and mojit data structures. I'm doing similar, @drewfish can explain more...

**Comment by isao** [comment]
i'm deleting the branch with the patch above, moved patch to https://gist.github.com/isao/5314079

**Comment by caridy** [comment]
closing this very old ticket, specially because we want to walk away from the store for many of the hacky stuff we were doing before mojito-next.
