### ISSUE TITLE
Is the search box not working currently?

### ISSUE THREAD

**Issue by nonopolarity** [YahooArchive/mojito#970]
Right now, say, if I go to 

http://developer.yahoo.com/cocktails/mojito/docs/intro/

and at the top left corner of the page, there is a search box, let's say I type in AJAX, and press Enter or click the Search icon, nothing happens?

**Comment by caridy** [comment]
/ping @zhouyaoji 

For the record, it works just fine for me.

**Comment by nonopolarity** [comment]
Later on, I found out when there is any search result, the result is shown, but if there is no result, there is not message on the page.  It simply stay the same as it was, giving the impression that nothing is happening.  Try entering `foobar` and do a search and it will show.

**Comment by zhouyaoji** [comment]
It worked fine for me, and when I search for a term that had no results such as "zzzzzz", the search page says that there were no results found. Closing bug. Thanks!
