### ISSUE TITLE
move yui javascript files out of the <head> tag

### ISSUE THREAD

**Issue by trungpham** [YahooArchive/mojito#976]
When using HTMLFrame and deploy=true. Mojito includes the following script tag in the head.

<script type="text/javascript" src="/combo~/static/yui/yui-base/yui-base-min.js~/static/yui/loader-base/loader-base-min.js~/static/yui/loader-yui3/loader-yui3-min.js~/static/loader-app.js~/static/loader-app-base.js"></script>

Can we move this seed tag to the bottom of the page so it won't block the page from rendering?

**Comment by caridy** [comment]
Started on 0.5.3, we are encouraging people to implement their own frame mojit. we did the provision for this by simplifying everything, so it becomes easy for anyone to set any mojit as a frame mojit, in which case you will control the view and the position of the elements at your convenience.

@zhouyaoji is working on the documentation, in the meantime, you can check this example:

https://github.com/caridy/Mojito-Apps
