### ISSUE TITLE
swapping out YUI Test

### ISSUE THREAD

**Issue by trungpham** [YahooArchive/mojito#986]
Is there any documentation around 'mojito test' command?

I would like to be able to replace YUITest with JasmineJS.

**Comment by isao** [comment]
@trungpham sorry unfortunately no docs beyond the code, which is due for refactoring after we move the cli commands into mojito-cli.

**Comment by caridy** [comment]
@isao can we move this ticket to the mojito-cli-test pkg?

**Comment by isao** [comment]
@trungpham I think this is a bit involved for the existing mojito test cli command, but definitely want to look into this. Closing here and tracking at yahoo/mojito-cli-test#1
