### ISSUE TITLE
[doc] missing comma between null NAME

### ISSUE THREAD

**Issue by emersonmatsumoto** [YahooArchive/mojito#991]
http://developer.yahoo.com/cocktails/mojito/docs/code_exs/simple_logging.html

3 Modify your controller so that one log message uses the default log level and one log message has the log level set by Y.log by replacing the code in controller.server.js with the following:

missing comma:  
Y.log('[CONTROLLER]: Default log-level message with date: ' + new Date(), null NAME);

**Comment by caridy** [comment]
@zhouyaoji will be great if we can fix this and also replace all the `null` with `"info"` or `"debug"`, which is the right thing to do.

**Comment by zhouyaoji** [comment]
@caridy The example is supposed to show that if you don't specify the log level in `Y.log`, the default ("info" in this example) defined in `application.json` is used.  Thus, explicitly specifying `info` or `debug` is counter to what that particular `Y.log` statement is trying to show. I'll fix the typo right right now.

**Comment by caridy** [comment]
Got it! thanks @zhouyaoji

**Comment by zhouyaoji** [comment]
Thanks, emersonmatsumoto! I've corrected the documentation.
