### ISSUE TITLE
[bz6101664] Mojito tunnel requests as GET to aid caching

### ISSUE THREAD

**Issue by swamib** [YahooArchive/mojito#992]
All the mojito invoke tunnel requests is using POST which does not facilitate caching at YTS / Edge layer. Allowing ability to use GET requests (making it configurable) and setting cache header for it would help the requests being served from Edge cache and reduce page latency.

**Comment by caridy** [comment]
mojito-next (0.9) allow you to do whatever you want with the tunnel middleware, but the problem with making calls thru GET is the payload size.

**Comment by caridy** [comment]
closing this in favor of issue #1050 which is a more realistic use case.
